# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.format_json_trivia import FormatJsonTrivia
from typing import Optional, Set
from typing_extensions import Self

class FormatJson(BaseModel):
    """
    FormatJson
    """ # noqa: E501
    copyright: Optional[StrictStr] = None
    copyright_link: Optional[StrictStr] = None
    var_date: Optional[StrictStr] = Field(default=None, alias="date")
    description: Optional[StrictStr] = None
    fetched_at: Optional[StrictStr] = None
    headline: Optional[StrictStr] = None
    image_url: Optional[StrictStr] = None
    image_url_1080: Optional[StrictStr] = None
    image_url_4k: Optional[StrictStr] = None
    market: Optional[StrictStr] = None
    quiz_id: Optional[StrictStr] = None
    resolution: Optional[StrictStr] = None
    subtitle: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    trivia: Optional[FormatJsonTrivia] = None
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["copyright", "copyright_link", "date", "description", "fetched_at", "headline", "image_url", "image_url_1080", "image_url_4k", "market", "quiz_id", "resolution", "subtitle", "title", "trivia", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FormatJson from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of trivia
        if self.trivia:
            _dict['trivia'] = self.trivia.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FormatJson from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "copyright": obj.get("copyright"),
            "copyright_link": obj.get("copyright_link"),
            "date": obj.get("date"),
            "description": obj.get("description"),
            "fetched_at": obj.get("fetched_at"),
            "headline": obj.get("headline"),
            "image_url": obj.get("image_url"),
            "image_url_1080": obj.get("image_url_1080"),
            "image_url_4k": obj.get("image_url_4k"),
            "market": obj.get("market"),
            "quiz_id": obj.get("quiz_id"),
            "resolution": obj.get("resolution"),
            "subtitle": obj.get("subtitle"),
            "title": obj.get("title"),
            "trivia": FormatJsonTrivia.from_dict(obj["trivia"]) if obj.get("trivia") is not None else None,
            "updated_at": obj.get("updated_at")
        })
        return _obj


