# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetSocialBilibiliArchives200ResponseVideosInner(BaseModel):
    """
    GetSocialBilibiliArchives200ResponseVideosInner
    """ # noqa: E501
    aid: Optional[StrictInt] = Field(default=None, description="视频AID")
    bvid: Optional[StrictStr] = Field(default=None, description="BV号")
    cover: Optional[StrictStr] = Field(default=None, description="封面URL")
    create_time: Optional[StrictInt] = Field(default=None, description="创建时间戳")
    duration: Optional[StrictInt] = Field(default=None, description="时长(秒)")
    is_interactive: Optional[StrictBool] = Field(default=None, description="是否为互动视频")
    is_ugc_pay: Optional[StrictInt] = Field(default=None, description="是否付费视频。0=免费，1=付费")
    play_count: Optional[StrictInt] = Field(default=None, description="播放量")
    publish_time: Optional[StrictInt] = Field(default=None, description="发布时间戳")
    state: Optional[StrictInt] = Field(default=None, description="视频状态")
    title: Optional[StrictStr] = Field(default=None, description="标题")
    __properties: ClassVar[List[str]] = ["aid", "bvid", "cover", "create_time", "duration", "is_interactive", "is_ugc_pay", "play_count", "publish_time", "state", "title"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetSocialBilibiliArchives200ResponseVideosInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetSocialBilibiliArchives200ResponseVideosInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "aid": obj.get("aid"),
            "bvid": obj.get("bvid"),
            "cover": obj.get("cover"),
            "create_time": obj.get("create_time"),
            "duration": obj.get("duration"),
            "is_interactive": obj.get("is_interactive"),
            "is_ugc_pay": obj.get("is_ugc_pay"),
            "play_count": obj.get("play_count"),
            "publish_time": obj.get("publish_time"),
            "state": obj.get("state"),
            "title": obj.get("title")
        })
        return _obj


