# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_github_user200_response_activity import GetGithubUser200ResponseActivity
from uapi.models.get_github_user200_response_organizations_inner import GetGithubUser200ResponseOrganizationsInner
from typing import Optional, Set
from typing_extensions import Self

class GetGithubUser200Response(BaseModel):
    """
    GetGithubUser200Response
    """ # noqa: E501
    login: Optional[StrictStr] = Field(default=None, description="GitHub 登录名。")
    name: Optional[StrictStr] = Field(default=None, description="用户公开显示的名称。")
    bio: Optional[StrictStr] = Field(default=None, description="用户个人简介。")
    company: Optional[StrictStr] = Field(default=None, description="用户填写的公司或组织信息。")
    location: Optional[StrictStr] = Field(default=None, description="用户公开展示的地理位置。")
    blog: Optional[StrictStr] = Field(default=None, description="用户填写的网站或博客地址。")
    twitter_username: Optional[StrictStr] = Field(default=None, description="用户绑定的 X（Twitter）用户名。")
    email: Optional[StrictStr] = Field(default=None, description="用户公开可见的邮箱地址。")
    html_url: Optional[StrictStr] = Field(default=None, description="GitHub 个人主页链接。")
    avatar_url: Optional[StrictStr] = Field(default=None, description="用户头像图片链接。")
    type: Optional[StrictStr] = Field(default=None, description="账号类型，常见值为 User 或 Organization。")
    public_repos: Optional[StrictInt] = Field(default=None, description="公开仓库数量。")
    public_gists: Optional[StrictInt] = Field(default=None, description="公开 Gist 数量。")
    followers: Optional[StrictInt] = Field(default=None, description="关注该用户的人数。")
    following: Optional[StrictInt] = Field(default=None, description="该用户正在关注的人数。")
    created_at: Optional[datetime] = Field(default=None, description="GitHub 账号创建时间（ISO 8601）。")
    updated_at: Optional[datetime] = Field(default=None, description="用户资料最近更新时间（ISO 8601）。")
    organizations: Optional[List[GetGithubUser200ResponseOrganizationsInner]] = Field(default=None, description="用户公开加入的组织列表")
    activity: Optional[GetGithubUser200ResponseActivity] = None
    __properties: ClassVar[List[str]] = ["login", "name", "bio", "company", "location", "blog", "twitter_username", "email", "html_url", "avatar_url", "type", "public_repos", "public_gists", "followers", "following", "created_at", "updated_at", "organizations", "activity"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGithubUser200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in organizations (list)
        _items = []
        if self.organizations:
            for _item_organizations in self.organizations:
                if _item_organizations:
                    _items.append(_item_organizations.to_dict())
            _dict['organizations'] = _items
        # override the default output from pydantic by calling `to_dict()` of activity
        if self.activity:
            _dict['activity'] = self.activity.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGithubUser200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "login": obj.get("login"),
            "name": obj.get("name"),
            "bio": obj.get("bio"),
            "company": obj.get("company"),
            "location": obj.get("location"),
            "blog": obj.get("blog"),
            "twitter_username": obj.get("twitter_username"),
            "email": obj.get("email"),
            "html_url": obj.get("html_url"),
            "avatar_url": obj.get("avatar_url"),
            "type": obj.get("type"),
            "public_repos": obj.get("public_repos"),
            "public_gists": obj.get("public_gists"),
            "followers": obj.get("followers"),
            "following": obj.get("following"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "organizations": [GetGithubUser200ResponseOrganizationsInner.from_dict(_item) for _item in obj["organizations"]] if obj.get("organizations") is not None else None,
            "activity": GetGithubUser200ResponseActivity.from_dict(obj["activity"]) if obj.get("activity") is not None else None
        })
        return _obj


