# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_misc_tracking_detect200_response_data_alternatives_inner import GetMiscTrackingDetect200ResponseDataAlternativesInner
from typing import Optional, Set
from typing_extensions import Self

class GetMiscTrackingDetect200ResponseData(BaseModel):
    """
    GetMiscTrackingDetect200ResponseData
    """ # noqa: E501
    tracking_number: Optional[StrictStr] = Field(default=None, description="查询的快递单号")
    carrier_code: Optional[StrictStr] = Field(default=None, description="最可能的快递公司编码")
    carrier_name: Optional[StrictStr] = Field(default=None, description="最可能的快递公司名称")
    alternatives: Optional[List[GetMiscTrackingDetect200ResponseDataAlternativesInner]] = Field(default=None, description="其他可能的快递公司列表（如果存在）")
    __properties: ClassVar[List[str]] = ["tracking_number", "carrier_code", "carrier_name", "alternatives"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetMiscTrackingDetect200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in alternatives (list)
        _items = []
        if self.alternatives:
            for _item_alternatives in self.alternatives:
                if _item_alternatives:
                    _items.append(_item_alternatives.to_dict())
            _dict['alternatives'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetMiscTrackingDetect200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tracking_number": obj.get("tracking_number"),
            "carrier_code": obj.get("carrier_code"),
            "carrier_name": obj.get("carrier_name"),
            "alternatives": [GetMiscTrackingDetect200ResponseDataAlternativesInner.from_dict(_item) for _item in obj["alternatives"]] if obj.get("alternatives") is not None else None
        })
        return _obj


