# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GetNetworkMyip200Response(BaseModel):
    """
    GetNetworkMyip200Response
    """ # noqa: E501
    asn: Optional[StrictStr] = Field(default=None, description="自治系统编号")
    beginip: Optional[StrictStr] = Field(default=None, description="IP段起始地址（标准查询）")
    district: Optional[StrictStr] = Field(default=None, description="行政区。仅 `source=commercial` 时可能返回。")
    endip: Optional[StrictStr] = Field(default=None, description="IP段结束地址（标准查询）")
    ip: Optional[StrictStr] = Field(default=None, description="你的公网IP地址")
    isp: Optional[StrictStr] = Field(default=None, description="运营商名称")
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="纬度")
    llc: Optional[StrictStr] = Field(default=None, description="归属机构")
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="经度")
    region: Optional[StrictStr] = Field(default=None, description="地理位置，格式：国家 省份 城市")
    time_zone: Optional[StrictStr] = Field(default=None, description="时区名称。仅 `source=commercial` 时可能返回。")
    __properties: ClassVar[List[str]] = ["asn", "beginip", "district", "endip", "ip", "isp", "latitude", "llc", "longitude", "region", "time_zone"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetNetworkMyip200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetNetworkMyip200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "asn": obj.get("asn"),
            "beginip": obj.get("beginip"),
            "district": obj.get("district"),
            "endip": obj.get("endip"),
            "ip": obj.get("ip"),
            "isp": obj.get("isp"),
            "latitude": obj.get("latitude"),
            "llc": obj.get("llc"),
            "longitude": obj.get("longitude"),
            "region": obj.get("region"),
            "time_zone": obj.get("time_zone")
        })
        return _obj


