# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetMiscHolidayCalendar200ResponseDaysInner(BaseModel):
    """
    GetMiscHolidayCalendar200ResponseDaysInner
    """ # noqa: E501
    var_date: Optional[StrictStr] = Field(default=None, description="公历日期（YYYY-MM-DD）。", alias="date")
    year: Optional[StrictInt] = Field(default=None, description="公历年份。")
    month: Optional[StrictInt] = Field(default=None, description="公历月份。")
    day: Optional[StrictInt] = Field(default=None, description="公历日期（天）。")
    weekday_cn: Optional[StrictStr] = Field(default=None, description="中文星期，如星期三。")
    is_weekend: Optional[StrictBool] = Field(default=None, description="是否为周末。")
    is_workday: Optional[StrictBool] = Field(default=None, description="是否为工作日（含法定调休上班日）。")
    is_rest_day: Optional[StrictBool] = Field(default=None, description="是否为休息日。")
    is_holiday: Optional[StrictBool] = Field(default=None, description="当天是否存在节日、节气或法定事件。")
    legal_holiday_name: Optional[StrictStr] = Field(default=None, description="法定节假日名称，无则为空或不返回。")
    legal_holiday_type: Optional[StrictStr] = Field(default=None, description="法定假日类型：rest 或 workday_adjust。")
    solar_festival: Optional[StrictStr] = Field(default=None, description="公历节日名称。有值时返回。")
    lunar_festival: Optional[StrictStr] = Field(default=None, description="农历节日名称。有值时返回。")
    solar_term: Optional[StrictStr] = Field(default=None, description="节气名称。有值时返回。")
    lunar_year: Optional[StrictInt] = Field(default=None, description="农历年份（数字）。")
    lunar_month: Optional[StrictInt] = Field(default=None, description="农历月份（数字）。")
    lunar_day: Optional[StrictInt] = Field(default=None, description="农历日期（数字）。")
    lunar_month_name: Optional[StrictStr] = Field(default=None, description="农历月份中文名称。")
    lunar_day_name: Optional[StrictStr] = Field(default=None, description="农历日期中文名称。")
    ganzhi_year: Optional[StrictStr] = Field(default=None, description="干支年。")
    ganzhi_month: Optional[StrictStr] = Field(default=None, description="干支月。")
    ganzhi_day: Optional[StrictStr] = Field(default=None, description="干支日。")
    __properties: ClassVar[List[str]] = ["date", "year", "month", "day", "weekday_cn", "is_weekend", "is_workday", "is_rest_day", "is_holiday", "legal_holiday_name", "legal_holiday_type", "solar_festival", "lunar_festival", "solar_term", "lunar_year", "lunar_month", "lunar_day", "lunar_month_name", "lunar_day_name", "ganzhi_year", "ganzhi_month", "ganzhi_day"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetMiscHolidayCalendar200ResponseDaysInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetMiscHolidayCalendar200ResponseDaysInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "date": obj.get("date"),
            "year": obj.get("year"),
            "month": obj.get("month"),
            "day": obj.get("day"),
            "weekday_cn": obj.get("weekday_cn"),
            "is_weekend": obj.get("is_weekend"),
            "is_workday": obj.get("is_workday"),
            "is_rest_day": obj.get("is_rest_day"),
            "is_holiday": obj.get("is_holiday"),
            "legal_holiday_name": obj.get("legal_holiday_name"),
            "legal_holiday_type": obj.get("legal_holiday_type"),
            "solar_festival": obj.get("solar_festival"),
            "lunar_festival": obj.get("lunar_festival"),
            "solar_term": obj.get("solar_term"),
            "lunar_year": obj.get("lunar_year"),
            "lunar_month": obj.get("lunar_month"),
            "lunar_day": obj.get("lunar_day"),
            "lunar_month_name": obj.get("lunar_month_name"),
            "lunar_day_name": obj.get("lunar_day_name"),
            "ganzhi_year": obj.get("ganzhi_year"),
            "ganzhi_month": obj.get("ganzhi_month"),
            "ganzhi_day": obj.get("ganzhi_day")
        })
        return _obj


