# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_social_qq_userinfo200_response_privilege_icons import GetSocialQqUserinfo200ResponsePrivilegeIcons
from typing import Optional, Set
from typing_extensions import Self

class GetSocialQqUserinfo200Response(BaseModel):
    """
    GetSocialQqUserinfo200Response
    """ # noqa: E501
    age: Optional[StrictInt] = Field(default=None, description="年龄")
    avatar_url: Optional[StrictStr] = Field(default=None, description="头像URL")
    big_club_level: Optional[StrictInt] = Field(default=None, description="QQ大会员等级")
    email: Optional[StrictStr] = Field(default=None, description="QQ邮箱")
    green_diamond_level: Optional[StrictInt] = Field(default=None, description="绿钻等级（可选）")
    is_big_club: Optional[StrictBool] = Field(default=None, description="是否为QQ大会员用户")
    is_svip: Optional[StrictBool] = Field(default=None, description="是否为SVIP用户")
    is_vip: Optional[StrictBool] = Field(default=None, description="是否为VIP用户")
    is_years_vip: Optional[StrictBool] = Field(default=None, description="是否为年费VIP用户")
    last_updated: Optional[StrictStr] = Field(default=None, description="最后更新时间（ISO 8601格式）")
    location: Optional[StrictStr] = Field(default=None, description="地理位置（省市）")
    long_nick: Optional[StrictStr] = Field(default=None, description="个性签名")
    lover_vip_level: Optional[StrictInt] = Field(default=None, description="情侣/恋人类会员等级（可选）")
    nickname: Optional[StrictStr] = Field(default=None, description="用户昵称")
    privilege_icons: Optional[GetSocialQqUserinfo200ResponsePrivilegeIcons] = None
    qid: Optional[StrictStr] = Field(default=None, description="QQ个性域名")
    qq: Optional[StrictStr] = Field(default=None, description="QQ号")
    qq_level: Optional[StrictInt] = Field(default=None, description="QQ等级。用户隐藏时返回 null")
    reg_time: Optional[StrictStr] = Field(default=None, description="注册时间（ISO 8601格式）")
    sex: Optional[StrictStr] = Field(default=None, description="性别")
    video_vip_level: Optional[StrictInt] = Field(default=None, description="腾讯影视会员等级（可选）")
    vip_level: Optional[StrictInt] = Field(default=None, description="VIP等级")
    vip_status: Optional[StrictInt] = Field(default=None, description="会员开通状态")
    vip_type: Optional[StrictInt] = Field(default=None, description="会员类型")
    yellow_diamond_level: Optional[StrictInt] = Field(default=None, description="黄钻等级（可选）")
    __properties: ClassVar[List[str]] = ["age", "avatar_url", "big_club_level", "email", "green_diamond_level", "is_big_club", "is_svip", "is_vip", "is_years_vip", "last_updated", "location", "long_nick", "lover_vip_level", "nickname", "privilege_icons", "qid", "qq", "qq_level", "reg_time", "sex", "video_vip_level", "vip_level", "vip_status", "vip_type", "yellow_diamond_level"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetSocialQqUserinfo200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of privilege_icons
        if self.privilege_icons:
            _dict['privilege_icons'] = self.privilege_icons.to_dict()
        # set to None if qq_level (nullable) is None
        # and model_fields_set contains the field
        if self.qq_level is None and "qq_level" in self.model_fields_set:
            _dict['qq_level'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetSocialQqUserinfo200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "age": obj.get("age"),
            "avatar_url": obj.get("avatar_url"),
            "big_club_level": obj.get("big_club_level"),
            "email": obj.get("email"),
            "green_diamond_level": obj.get("green_diamond_level"),
            "is_big_club": obj.get("is_big_club"),
            "is_svip": obj.get("is_svip"),
            "is_vip": obj.get("is_vip"),
            "is_years_vip": obj.get("is_years_vip"),
            "last_updated": obj.get("last_updated"),
            "location": obj.get("location"),
            "long_nick": obj.get("long_nick"),
            "lover_vip_level": obj.get("lover_vip_level"),
            "nickname": obj.get("nickname"),
            "privilege_icons": GetSocialQqUserinfo200ResponsePrivilegeIcons.from_dict(obj["privilege_icons"]) if obj.get("privilege_icons") is not None else None,
            "qid": obj.get("qid"),
            "qq": obj.get("qq"),
            "qq_level": obj.get("qq_level"),
            "reg_time": obj.get("reg_time"),
            "sex": obj.get("sex"),
            "video_vip_level": obj.get("video_vip_level"),
            "vip_level": obj.get("vip_level"),
            "vip_status": obj.get("vip_status"),
            "vip_type": obj.get("vip_type"),
            "yellow_diamond_level": obj.get("yellow_diamond_level")
        })
        return _obj


