# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uapi.models.get_web_tomarkdown_async_status200_response_any_of2_result import GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result
from typing import Optional, Set
from typing_extensions import Self

class GetWebTomarkdownAsyncStatus200ResponseAnyOf2(BaseModel):
    """
    GetWebTomarkdownAsyncStatus200ResponseAnyOf2
    """ # noqa: E501
    completed_at: Optional[StrictStr] = None
    created_at: Optional[StrictStr] = None
    duration: Optional[Union[StrictFloat, StrictInt]] = None
    progress: Optional[StrictInt] = None
    result: Optional[GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result] = None
    started_at: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    task_id: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["completed_at", "created_at", "duration", "progress", "result", "started_at", "status", "task_id", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict['result'] = self.result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetWebTomarkdownAsyncStatus200ResponseAnyOf2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "duration": obj.get("duration"),
            "progress": obj.get("progress"),
            "result": GetWebTomarkdownAsyncStatus200ResponseAnyOf2Result.from_dict(obj["result"]) if obj.get("result") is not None else None,
            "started_at": obj.get("started_at"),
            "status": obj.get("status"),
            "task_id": obj.get("task_id"),
            "url": obj.get("url")
        })
        return _obj


