# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GetSocialBilibiliVideoinfo200ResponseStat(BaseModel):
    """
    视频的核心数据统计。
    """ # noqa: E501
    view: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="播放数。")
    danmaku: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="弹幕数。")
    reply: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="评论数。")
    favorite: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="收藏数。")
    coin: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="投币数。")
    share: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="分享数。")
    like: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="获赞数。")
    __properties: ClassVar[List[str]] = ["view", "danmaku", "reply", "favorite", "coin", "share", "like"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetSocialBilibiliVideoinfo200ResponseStat from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetSocialBilibiliVideoinfo200ResponseStat from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "view": obj.get("view"),
            "danmaku": obj.get("danmaku"),
            "reply": obj.get("reply"),
            "favorite": obj.get("favorite"),
            "coin": obj.get("coin"),
            "share": obj.get("share"),
            "like": obj.get("like")
        })
        return _obj


