# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_game_minecraft_historyid200_response_history_inner import GetGameMinecraftHistoryid200ResponseHistoryInner
from uapi.models.get_game_minecraft_historyid200_response_results_inner import GetGameMinecraftHistoryid200ResponseResultsInner
from typing import Optional, Set
from typing_extensions import Self

class GetGameMinecraftHistoryid200Response(BaseModel):
    """
    响应结构根据查询参数不同而变化
    """ # noqa: E501
    query: Optional[StrictStr] = Field(default=None, description="【name 查询时返回】查询的用户名。")
    count: Optional[StrictInt] = Field(default=None, description="【name 查询时返回】匹配到的用户数量，为 0 时表示未找到。")
    results: Optional[List[GetGameMinecraftHistoryid200ResponseResultsInner]] = Field(default=None, description="【name 查询时返回】匹配用户列表，包含当前用户名或曾用名匹配的所有玩家。")
    id: Optional[StrictStr] = Field(default=None, description="【uuid 查询时返回】玩家当前的用户名。")
    uuid: Optional[StrictStr] = Field(default=None, description="【uuid 查询时返回】被查询玩家的UUID（带连字符格式）。")
    name_num: Optional[StrictInt] = Field(default=None, description="【uuid 查询时返回】历史名称的总数（包含当前名称）。")
    history: Optional[List[GetGameMinecraftHistoryid200ResponseHistoryInner]] = Field(default=None, description="【uuid 查询时返回】包含所有历史用户名的数组，按时间倒序排列。")
    __properties: ClassVar[List[str]] = ["query", "count", "results", "id", "uuid", "name_num", "history"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGameMinecraftHistoryid200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in results (list)
        _items = []
        if self.results:
            for _item_results in self.results:
                if _item_results:
                    _items.append(_item_results.to_dict())
            _dict['results'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict['history'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGameMinecraftHistoryid200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "query": obj.get("query"),
            "count": obj.get("count"),
            "results": [GetGameMinecraftHistoryid200ResponseResultsInner.from_dict(_item) for _item in obj["results"]] if obj.get("results") is not None else None,
            "id": obj.get("id"),
            "uuid": obj.get("uuid"),
            "name_num": obj.get("name_num"),
            "history": [GetGameMinecraftHistoryid200ResponseHistoryInner.from_dict(_item) for _item in obj["history"]] if obj.get("history") is not None else None
        })
        return _obj


