# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_github_user200_response_activity_contribution_calendar_weeks_inner import GetGithubUser200ResponseActivityContributionCalendarWeeksInner
from typing import Optional, Set
from typing_extensions import Self

class GetGithubUser200ResponseActivityContributionCalendar(BaseModel):
    """
    按周整理好的贡献日历数据。
    """ # noqa: E501
    colors: Optional[List[StrictStr]] = Field(default=None, description="贡献等级对应的颜色列表。")
    is_halloween: Optional[StrictBool] = Field(default=None, description="是否启用了 GitHub 万圣节配色主题。")
    total_contributions: Optional[StrictInt] = Field(default=None, description="贡献日历中的总贡献数。")
    weeks: Optional[List[GetGithubUser200ResponseActivityContributionCalendarWeeksInner]] = Field(default=None, description="按周排列的贡献日历列数据。")
    __properties: ClassVar[List[str]] = ["colors", "is_halloween", "total_contributions", "weeks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGithubUser200ResponseActivityContributionCalendar from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in weeks (list)
        _items = []
        if self.weeks:
            for _item_weeks in self.weeks:
                if _item_weeks:
                    _items.append(_item_weeks.to_dict())
            _dict['weeks'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGithubUser200ResponseActivityContributionCalendar from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "colors": obj.get("colors"),
            "is_halloween": obj.get("is_halloween"),
            "total_contributions": obj.get("total_contributions"),
            "weeks": [GetGithubUser200ResponseActivityContributionCalendarWeeksInner.from_dict(_item) for _item in obj["weeks"]] if obj.get("weeks") is not None else None
        })
        return _obj


