# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.get_game_minecraft_historyid200_response_history_inner import GetGameMinecraftHistoryid200ResponseHistoryInner
from typing import Optional, Set
from typing_extensions import Self

class GetGameMinecraftHistoryid200Response(BaseModel):
    """
    GetGameMinecraftHistoryid200Response
    """ # noqa: E501
    code: Optional[StrictInt] = Field(default=None, description="状态码，200代表成功。")
    history: Optional[List[GetGameMinecraftHistoryid200ResponseHistoryInner]] = Field(default=None, description="一个包含所有历史用户名的数组，按时间倒序排列。")
    id: Optional[StrictStr] = Field(default=None, description="玩家当前的用户名。")
    name_num: Optional[StrictInt] = Field(default=None, description="历史名称的总数（包含当前名称）。")
    uuid: Optional[StrictStr] = Field(default=None, description="被查询玩家的32位无破折号UUID。")
    __properties: ClassVar[List[str]] = ["code", "history", "id", "name_num", "uuid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGameMinecraftHistoryid200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in history (list)
        _items = []
        if self.history:
            for _item_history in self.history:
                if _item_history:
                    _items.append(_item_history.to_dict())
            _dict['history'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGameMinecraftHistoryid200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "history": [GetGameMinecraftHistoryid200ResponseHistoryInner.from_dict(_item) for _item in obj["history"]] if obj.get("history") is not None else None,
            "id": obj.get("id"),
            "name_num": obj.get("name_num"),
            "uuid": obj.get("uuid")
        })
        return _obj


