# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class GetGameEpicFree200ResponseDataInner(BaseModel):
    """
    GetGameEpicFree200ResponseDataInner
    """ # noqa: E501
    id: Optional[StrictStr] = Field(default=None, description="游戏的唯一标识ID。")
    title: Optional[StrictStr] = Field(default=None, description="游戏的完整标题名称。")
    cover: Optional[StrictStr] = Field(default=None, description="游戏封面图片的URL地址。")
    original_price: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="游戏的原价，单位为人民币元。")
    original_price_desc: Optional[StrictStr] = Field(default=None, description="格式化后的原价描述字符串。")
    description: Optional[StrictStr] = Field(default=None, description="游戏的简介描述。")
    seller: Optional[StrictStr] = Field(default=None, description="游戏的发行商或销售商。")
    is_free_now: Optional[StrictBool] = Field(default=None, description="当前是否处于免费状态。")
    free_start: Optional[StrictStr] = Field(default=None, description="免费开始时间的可读字符串格式。")
    free_start_at: Optional[StrictInt] = Field(default=None, description="免费开始时间的13位毫秒时间戳。")
    free_end: Optional[StrictStr] = Field(default=None, description="免费结束时间的可读字符串格式。")
    free_end_at: Optional[StrictInt] = Field(default=None, description="免费结束时间的13位毫秒时间戳。")
    link: Optional[StrictStr] = Field(default=None, description="游戏在Epic Games商店的详情页链接。")
    __properties: ClassVar[List[str]] = ["id", "title", "cover", "original_price", "original_price_desc", "description", "seller", "is_free_now", "free_start", "free_start_at", "free_end", "free_end_at", "link"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetGameEpicFree200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetGameEpicFree200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "cover": obj.get("cover"),
            "original_price": obj.get("original_price"),
            "original_price_desc": obj.get("original_price_desc"),
            "description": obj.get("description"),
            "seller": obj.get("seller"),
            "is_free_now": obj.get("is_free_now"),
            "free_start": obj.get("free_start"),
            "free_start_at": obj.get("free_start_at"),
            "free_end": obj.get("free_end"),
            "free_end_at": obj.get("free_end_at"),
            "link": obj.get("link")
        })
        return _obj


