# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostWatermarkProducerCode200Response(BaseModel):
    """
    PostWatermarkProducerCode200Response
    """ # noqa: E501
    binding: Optional[StrictStr] = Field(default=None, description="解析出的证件绑定方式。")
    code: Optional[StrictStr] = Field(default=None, description="标准的 27 位服务提供者编码。")
    identifier: Optional[StrictStr] = Field(default=None, description="剔除补位后的主体证件原始明文。")
    model_code: Optional[StrictStr] = Field(default=None, description="解析出的模型/应用码（启用扩展时存在）。")
    service_extension: Optional[StrictBool] = Field(default=None, description="编码中是否启用了服务扩展段。")
    service_type: Optional[StrictStr] = Field(default=None, description="解析出的服务角色类型（启用扩展时存在）。")
    subject_code: Optional[StrictStr] = Field(default=None, description="包含补位逻辑在内的 18 位主体特征段。")
    subject_type: Optional[StrictStr] = Field(default=None, description="解析出的主体类型。")
    valid: Optional[StrictBool] = Field(default=None, description="该编码是否合规合法。")
    __properties: ClassVar[List[str]] = ["binding", "code", "identifier", "model_code", "service_extension", "service_type", "subject_code", "subject_type", "valid"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostWatermarkProducerCode200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostWatermarkProducerCode200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "binding": obj.get("binding"),
            "code": obj.get("code"),
            "identifier": obj.get("identifier"),
            "model_code": obj.get("model_code"),
            "service_extension": obj.get("service_extension"),
            "service_type": obj.get("service_type"),
            "subject_code": obj.get("subject_code"),
            "subject_type": obj.get("subject_type"),
            "valid": obj.get("valid")
        })
        return _obj


