# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uapi.models.post_image_ocr200_response_words_result_inner import PostImageOcr200ResponseWordsResultInner
from typing import Optional, Set
from typing_extensions import Self

class PostImageOcr200Response(BaseModel):
    """
    PostImageOcr200Response
    """ # noqa: E501
    blocks: Optional[List[Dict[str, Any]]] = Field(default=None, description="按块组织的详细识别结果。")
    image: Optional[Dict[str, Any]] = Field(default=None, description="图片本身的基础信息。")
    lines: Optional[List[Dict[str, Any]]] = Field(default=None, description="按行组织的详细识别结果。")
    markdown: Optional[StrictStr] = Field(default=None, description="根据图片中的标题、段落和表格整理出的 Markdown 文本。只有在 `return_markdown=true` 时才会返回。")
    need_location: Optional[StrictBool] = Field(default=None, description="本次响应是否包含坐标信息。")
    pages: Optional[List[Dict[str, Any]]] = Field(default=None, description="按页组织的详细识别结果。")
    plain_text: Optional[StrictStr] = Field(default=None, description="纯文本结果，适合做搜索、索引或直接展示。")
    raw: Optional[Dict[str, Any]] = Field(default=None, description="补充识别结果对象，适合需要继续解析更多细节字段的场景。")
    summary: Optional[Dict[str, Any]] = Field(default=None, description="识别结果的统计摘要。")
    text: Optional[StrictStr] = Field(default=None, description="按阅读顺序拼接后的识别文本。")
    timing: Optional[Dict[str, Any]] = Field(default=None, description="耗时拆分信息，适合做性能统计或排查。")
    words_result: Optional[List[PostImageOcr200ResponseWordsResultInner]] = Field(default=None, description="逐段文字结果。适合做高亮、框选和逐项解析。")
    words_result_num: Optional[StrictInt] = Field(default=None, description="识别出的文字片段数量。")
    __properties: ClassVar[List[str]] = ["blocks", "image", "lines", "markdown", "need_location", "pages", "plain_text", "raw", "summary", "text", "timing", "words_result", "words_result_num"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostImageOcr200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in words_result (list)
        _items = []
        if self.words_result:
            for _item_words_result in self.words_result:
                if _item_words_result:
                    _items.append(_item_words_result.to_dict())
            _dict['words_result'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostImageOcr200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blocks": obj.get("blocks"),
            "image": obj.get("image"),
            "lines": obj.get("lines"),
            "markdown": obj.get("markdown"),
            "need_location": obj.get("need_location"),
            "pages": obj.get("pages"),
            "plain_text": obj.get("plain_text"),
            "raw": obj.get("raw"),
            "summary": obj.get("summary"),
            "text": obj.get("text"),
            "timing": obj.get("timing"),
            "words_result": [PostImageOcr200ResponseWordsResultInner.from_dict(_item) for _item in obj["words_result"]] if obj.get("words_result") is not None else None,
            "words_result_num": obj.get("words_result_num")
        })
        return _obj


