# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PostWatermarkProducerCodeRequest(BaseModel):
    """
    PostWatermarkProducerCodeRequest
    """ # noqa: E501
    binding: Optional[StrictStr] = Field(default=None, description="主体绑定的证件类型。组织需使用统一社会信用代码；个人可选身份证、手机号、护照或网号。")
    code: Optional[StrictStr] = Field(default=None, description="待校验的 27 位现成编码。填写后接口将直接执行合法性校验。")
    identifier: Optional[StrictStr] = Field(default=None, description="证件号实际内容。长度需匹配选择的类型（如统一社会信用代码 18 位、手机号 11 位）。")
    model_code: Optional[StrictStr] = Field(default=None, description="4 位自定义模型或应用码（可选）。未提供时扩展段将默认填充 00000。")
    service_type: Optional[StrictStr] = Field(default=None, description="服务角色类型（仅在提供模型应用码时一同生效）。")
    subject_type: Optional[StrictStr] = Field(default=None, description="主体类型是组织还是个人。")
    __properties: ClassVar[List[str]] = ["binding", "code", "identifier", "model_code", "service_type", "subject_type"]

    @field_validator('binding')
    def binding_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['uscc', 'id', 'phone', 'passport', 'netid']):
            raise ValueError("must be one of enum values ('uscc', 'id', 'phone', 'passport', 'netid')")
        return value

    @field_validator('service_type')
    def service_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['generation', 'propagation']):
            raise ValueError("must be one of enum values ('generation', 'propagation')")
        return value

    @field_validator('subject_type')
    def subject_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['org', 'person']):
            raise ValueError("must be one of enum values ('org', 'person')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PostWatermarkProducerCodeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PostWatermarkProducerCodeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "binding": obj.get("binding"),
            "code": obj.get("code"),
            "identifier": obj.get("identifier"),
            "model_code": obj.get("model_code"),
            "service_type": obj.get("service_type"),
            "subject_type": obj.get("subject_type")
        })
        return _obj


