# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_search_aggregate200_response_metadata import PostSearchAggregate200ResponseMetadata

class TestPostSearchAggregate200ResponseMetadata(unittest.TestCase):
    """PostSearchAggregate200ResponseMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSearchAggregate200ResponseMetadata:
        """Test PostSearchAggregate200ResponseMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSearchAggregate200ResponseMetadata`
        """
        model = PostSearchAggregate200ResponseMetadata()
        if include_optional:
            return PostSearchAggregate200ResponseMetadata(
                request_params = uapi.models.post_search_aggregate_200_response_metadata_request_params.post_search_aggregate_200_response_metadata_request_params(
                    query = 'Go最新的版本是多少', 
                    limit = 10, 
                    page = 1, 
                    timeout_ms = 60000, 
                    sort = 'relevance', ),
                dedupe_removed = 0,
                rerank_applied = True,
                content_fetched = 0
            )
        else:
            return PostSearchAggregate200ResponseMetadata(
        )
        """

    def testPostSearchAggregate200ResponseMetadata(self):
        """Test PostSearchAggregate200ResponseMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
