# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_phoneinfo400_response import GetMiscPhoneinfo400Response

class TestGetMiscPhoneinfo400Response(unittest.TestCase):
    """GetMiscPhoneinfo400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscPhoneinfo400Response:
        """Test GetMiscPhoneinfo400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscPhoneinfo400Response`
        """
        model = GetMiscPhoneinfo400Response()
        if include_optional:
            return GetMiscPhoneinfo400Response(
                code = 'INVALID_ARGUMENT',
                details = None,
                message = 'Missing or invalid 'phone' parameter.'
            )
        else:
            return GetMiscPhoneinfo400Response(
        )
        """

    def testGetMiscPhoneinfo400Response(self):
        """Test GetMiscPhoneinfo400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
