# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_translate_stream_request import PostTranslateStreamRequest

class TestPostTranslateStreamRequest(unittest.TestCase):
    """PostTranslateStreamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTranslateStreamRequest:
        """Test PostTranslateStreamRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTranslateStreamRequest`
        """
        model = PostTranslateStreamRequest()
        if include_optional:
            return PostTranslateStreamRequest(
                query = 'Hello, how are you?',
                to_lang = '中文',
                from_lang = 'auto',
                tone = ''
            )
        else:
            return PostTranslateStreamRequest(
                query = 'Hello, how are you?',
                to_lang = '中文',
        )
        """

    def testPostTranslateStreamRequest(self):
        """Test PostTranslateStreamRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
