# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_translate_text500_response import PostTranslateText500Response

class TestPostTranslateText500Response(unittest.TestCase):
    """PostTranslateText500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTranslateText500Response:
        """Test PostTranslateText500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTranslateText500Response`
        """
        model = PostTranslateText500Response()
        if include_optional:
            return PostTranslateText500Response(
                code = 'TRANSLATION_FAILED',
                details = None,
                message = 'Translation failed due to an upstream service error.'
            )
        else:
            return PostTranslateText500Response(
        )
        """

    def testPostTranslateText500Response(self):
        """Test PostTranslateText500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
