# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_image_motou500_response import GetImageMotou500Response

class TestGetImageMotou500Response(unittest.TestCase):
    """GetImageMotou500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImageMotou500Response:
        """Test GetImageMotou500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImageMotou500Response`
        """
        model = GetImageMotou500Response()
        if include_optional:
            return GetImageMotou500Response(
                error = 'Failed to generate image'
            )
        else:
            return GetImageMotou500Response(
        )
        """

    def testGetImageMotou500Response(self):
        """Test GetImageMotou500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
