# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_image_nsfw400_response import PostImageNsfw400Response

class TestPostImageNsfw400Response(unittest.TestCase):
    """PostImageNsfw400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostImageNsfw400Response:
        """Test PostImageNsfw400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostImageNsfw400Response`
        """
        model = PostImageNsfw400Response()
        if include_optional:
            return PostImageNsfw400Response(
                code = 'INVALID_ARGUMENT',
                message = '必须提供图片文件或图片URL'
            )
        else:
            return PostImageNsfw400Response(
        )
        """

    def testPostImageNsfw400Response(self):
        """Test PostImageNsfw400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
