# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_status_usage404_response import GetStatusUsage404Response

class TestGetStatusUsage404Response(unittest.TestCase):
    """GetStatusUsage404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetStatusUsage404Response:
        """Test GetStatusUsage404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetStatusUsage404Response`
        """
        model = GetStatusUsage404Response()
        if include_optional:
            return GetStatusUsage404Response(
                code = 'NOT_FOUND',
                details = None,
                message = 'No usage statistics found for the specified path.'
            )
        else:
            return GetStatusUsage404Response(
        )
        """

    def testGetStatusUsage404Response(self):
        """Test GetStatusUsage404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
