# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_text_markdown_to_pdf413_response import PostTextMarkdownToPdf413Response

class TestPostTextMarkdownToPdf413Response(unittest.TestCase):
    """PostTextMarkdownToPdf413Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTextMarkdownToPdf413Response:
        """Test PostTextMarkdownToPdf413Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTextMarkdownToPdf413Response`
        """
        model = PostTextMarkdownToPdf413Response()
        if include_optional:
            return PostTextMarkdownToPdf413Response(
                code = 'FILE_TOO_LARGE',
                message = 'Markdown 中的图片体积过大，请换一张更小的图片再试'
            )
        else:
            return PostTextMarkdownToPdf413Response(
        )
        """

    def testPostTextMarkdownToPdf413Response(self):
        """Test PostTextMarkdownToPdf413Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
