# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_network_ipinfo200_response import GetNetworkIpinfo200Response

class TestGetNetworkIpinfo200Response(unittest.TestCase):
    """GetNetworkIpinfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkIpinfo200Response:
        """Test GetNetworkIpinfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkIpinfo200Response`
        """
        model = GetNetworkIpinfo200Response()
        if include_optional:
            return GetNetworkIpinfo200Response(
                asn = 'AS15169',
                beginip = '8.8.8.0',
                code = 200,
                endip = '8.8.8.255',
                ip = '8.8.8.8',
                isp = 'Google',
                latitude = 37.386,
                llc = 'Google LLC',
                longitude = -122.0838,
                region = '美国 加利福尼亚州 圣克拉拉县',
                district = '临桂',
                area_code = '450312',
                city_code = '0773',
                zip_code = '541100',
                time_zone = 'Asia/Shanghai',
                scenes = '企业数据',
                elevation = '155',
                weather_station = 'CHXX0434'
            )
        else:
            return GetNetworkIpinfo200Response(
        )
        """

    def testGetNetworkIpinfo200Response(self):
        """Test GetNetworkIpinfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
