# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_clipzy_raw400_response import GetClipzyRaw400Response

class TestGetClipzyRaw400Response(unittest.TestCase):
    """GetClipzyRaw400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetClipzyRaw400Response:
        """Test GetClipzyRaw400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetClipzyRaw400Response`
        """
        model = GetClipzyRaw400Response()
        if include_optional:
            return GetClipzyRaw400Response(
                error = 'Invalid or missing ID/key.'
            )
        else:
            return GetClipzyRaw400Response(
        )
        """

    def testGetClipzyRaw400Response(self):
        """Test GetClipzyRaw400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
