# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_game_minecraft_userinfo200_response import GetGameMinecraftUserinfo200Response

class TestGetGameMinecraftUserinfo200Response(unittest.TestCase):
    """GetGameMinecraftUserinfo200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGameMinecraftUserinfo200Response:
        """Test GetGameMinecraftUserinfo200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGameMinecraftUserinfo200Response`
        """
        model = GetGameMinecraftUserinfo200Response()
        if include_optional:
            return GetGameMinecraftUserinfo200Response(
                code = 200,
                skin_url = 'http://textures.minecraft.net/texture/292009a499420915b854a9913d9fa92750175814529452a55982791844863f53',
                username = 'Notch',
                uuid = 'ee9b4ed1aac1491eb7611471be374b80'
            )
        else:
            return GetGameMinecraftUserinfo200Response(
        )
        """

    def testGetGameMinecraftUserinfo200Response(self):
        """Test GetGameMinecraftUserinfo200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
