# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_social_bilibili_replies200_response_page import GetSocialBilibiliReplies200ResponsePage

class TestGetSocialBilibiliReplies200ResponsePage(unittest.TestCase):
    """GetSocialBilibiliReplies200ResponsePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSocialBilibiliReplies200ResponsePage:
        """Test GetSocialBilibiliReplies200ResponsePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSocialBilibiliReplies200ResponsePage`
        """
        model = GetSocialBilibiliReplies200ResponsePage()
        if include_optional:
            return GetSocialBilibiliReplies200ResponsePage(
                num = 1,
                size = 5,
                count = 81682,
                acount = 123456
            )
        else:
            return GetSocialBilibiliReplies200ResponsePage(
        )
        """

    def testGetSocialBilibiliReplies200ResponsePage(self):
        """Test GetSocialBilibiliReplies200ResponsePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
