# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_github_user200_response import GetGithubUser200Response

class TestGetGithubUser200Response(unittest.TestCase):
    """GetGithubUser200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGithubUser200Response:
        """Test GetGithubUser200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGithubUser200Response`
        """
        model = GetGithubUser200Response()
        if include_optional:
            return GetGithubUser200Response(
                login = 'torvalds',
                name = 'Linus Torvalds',
                bio = 'Linux kernel creator',
                company = 'Linux Foundation',
                location = 'Portland, OR',
                blog = '',
                twitter_username = '',
                email = '',
                html_url = 'https://github.com/torvalds',
                avatar_url = 'https://avatars.githubusercontent.com/u/1024025?v=4',
                type = 'User',
                public_repos = 8,
                public_gists = 0,
                followers = 100,
                following = 0,
                created_at = '2011-09-03T15:26:22Z',
                updated_at = '2026-04-12T00:00Z',
                organizations = [
                    uapi.models.get_github_user_200_response_organizations_inner.get_github_user_200_response_organizations_inner(
                        login = 'linux-foundation', 
                        description = 'Open source organization', 
                        html_url = 'https://github.com/linux-foundation', 
                        avatar_url = 'https://avatars.githubusercontent.com/u/123456?v=4', )
                    ],
                activity = uapi.models.get_github_user_200_response_activity.get_github_user_200_response_activity(
                    scope = 'organization', 
                    organization = 'linux-foundation', 
                    from = '2025-04-12', 
                    to = '2026-04-12', 
                    total_contributions = 4, 
                    total_commit_contributions = 2, 
                    total_issue_contributions = 1, 
                    total_pull_request_contributions = 1, 
                    total_pull_request_review_contributions = 0, 
                    contribution_calendar = uapi.models.get_github_user_200_response_activity_contribution_calendar.get_github_user_200_response_activity_contribution_calendar(
                        colors = ["#ebedf0","#40c463"], 
                        is_halloween = False, 
                        total_contributions = 4, 
                        weeks = [
                            uapi.models.get_github_user_200_response_activity_contribution_calendar_weeks_inner.get_github_user_200_response_activity_contribution_calendar_weeks_inner(
                                first_day = '2026-04-06', 
                                contribution_days = [
                                    uapi.models.get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner.get_github_user_200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner(
                                        date = '2026-04-07', 
                                        contribution_count = 1, 
                                        color = '#40c463', 
                                        weekday = 2, )
                                    ], )
                            ], ), 
                    timeline = [
                        uapi.models.get_github_user_200_response_activity_timeline_inner.get_github_user_200_response_activity_timeline_inner(
                            month = '2026-04', 
                            contribution_count = 4, )
                        ], )
            )
        else:
            return GetGithubUser200Response(
        )
        """

    def testGetGithubUser200Response(self):
        """Test GetGithubUser200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
