# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_answerbook_ask200_response import GetAnswerbookAsk200Response

class TestGetAnswerbookAsk200Response(unittest.TestCase):
    """GetAnswerbookAsk200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAnswerbookAsk200Response:
        """Test GetAnswerbookAsk200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAnswerbookAsk200Response`
        """
        model = GetAnswerbookAsk200Response()
        if include_optional:
            return GetAnswerbookAsk200Response(
                code = 200,
                question = '我今天会有好运吗？',
                answer = '一切都会好起来'
            )
        else:
            return GetAnswerbookAsk200Response(
        )
        """

    def testGetAnswerbookAsk200Response(self):
        """Test GetAnswerbookAsk200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
