# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.endpoints_aggregate_unaggregated import EndpointsAggregateUnaggregated

class TestEndpointsAggregateUnaggregated(unittest.TestCase):
    """EndpointsAggregateUnaggregated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EndpointsAggregateUnaggregated:
        """Test EndpointsAggregateUnaggregated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EndpointsAggregateUnaggregated`
        """
        model = EndpointsAggregateUnaggregated()
        if include_optional:
            return EndpointsAggregateUnaggregated(
                count = 356,
                oldest_log = '2025-11-09T23:52:38.929+08:00'
            )
        else:
            return EndpointsAggregateUnaggregated(
        )
        """

    def testEndpointsAggregateUnaggregated(self):
        """Test EndpointsAggregateUnaggregated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
