# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_game_steam_summary200_response import GetGameSteamSummary200Response

class TestGetGameSteamSummary200Response(unittest.TestCase):
    """GetGameSteamSummary200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGameSteamSummary200Response:
        """Test GetGameSteamSummary200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGameSteamSummary200Response`
        """
        model = GetGameSteamSummary200Response()
        if include_optional:
            return GetGameSteamSummary200Response(
                avatar = 'https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb.jpg',
                avatarfull = 'https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_full.jpg',
                avatarmedium = 'https://avatars.steamstatic.com/fef49e7fa7e1997310d705b2a6158ff8dc1cdfeb_medium.jpg',
                code = 200,
                communityvisibilitystate = 3,
                loccountrycode = 'US',
                personaname = 'Gabe Newell',
                personastate = 1,
                primaryclanid = '103582791429521412',
                profilestate = 1,
                profileurl = 'https://steamcommunity.com/id/gabelogannewell/',
                realname = 'Gabe Logan Newell',
                steamid = '76561197960435530',
                timecreated = 1063407589,
                timecreated_str = '2003-09-12 22:59:49'
            )
        else:
            return GetGameSteamSummary200Response(
        )
        """

    def testGetGameSteamSummary200Response(self):
        """Test GetGameSteamSummary200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
