# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_forecast_inner import GetMiscWeather200ResponseForecastInner

class TestGetMiscWeather200ResponseForecastInner(unittest.TestCase):
    """GetMiscWeather200ResponseForecastInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseForecastInner:
        """Test GetMiscWeather200ResponseForecastInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseForecastInner`
        """
        model = GetMiscWeather200ResponseForecastInner()
        if include_optional:
            return GetMiscWeather200ResponseForecastInner(
                var_date = '2026-02-19',
                week = '星期四',
                temp_max = 14,
                temp_min = -1,
                weather_day = '晴',
                weather_night = '晴',
                wind_dir_day = '西南风',
                wind_dir_night = '北风',
                wind_scale_day = '微风',
                wind_scale_night = '微风',
                wind_speed_day = 17,
                humidity = 40,
                precip = 0,
                visibility = 25,
                uv_index = 5,
                sunrise = '06:52',
                sunset = '1076'
            )
        else:
            return GetMiscWeather200ResponseForecastInner(
        )
        """

    def testGetMiscWeather200ResponseForecastInner(self):
        """Test GetMiscWeather200ResponseForecastInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
