# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_ai_translate401_response import PostAiTranslate401Response

class TestPostAiTranslate401Response(unittest.TestCase):
    """PostAiTranslate401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAiTranslate401Response:
        """Test PostAiTranslate401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAiTranslate401Response`
        """
        model = PostAiTranslate401Response()
        if include_optional:
            return PostAiTranslate401Response(
                code = 401,
                message = 'Unauthorized',
                error = 'Invalid or missing API token'
            )
        else:
            return PostAiTranslate401Response(
        )
        """

    def testPostAiTranslate401Response(self):
        """Test PostAiTranslate401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
