# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_sensitive_word_analyze_query400_response import GetSensitiveWordAnalyzeQuery400Response

class TestGetSensitiveWordAnalyzeQuery400Response(unittest.TestCase):
    """GetSensitiveWordAnalyzeQuery400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSensitiveWordAnalyzeQuery400Response:
        """Test GetSensitiveWordAnalyzeQuery400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSensitiveWordAnalyzeQuery400Response`
        """
        model = GetSensitiveWordAnalyzeQuery400Response()
        if include_optional:
            return GetSensitiveWordAnalyzeQuery400Response(
                code = 'INVALID_PARAMETER',
                message = '关键词不能为空'
            )
        else:
            return GetSensitiveWordAnalyzeQuery400Response(
        )
        """

    def testGetSensitiveWordAnalyzeQuery400Response(self):
        """Test GetSensitiveWordAnalyzeQuery400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
