# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_image_qrcode400_response import GetImageQrcode400Response

class TestGetImageQrcode400Response(unittest.TestCase):
    """GetImageQrcode400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImageQrcode400Response:
        """Test GetImageQrcode400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImageQrcode400Response`
        """
        model = GetImageQrcode400Response()
        if include_optional:
            return GetImageQrcode400Response(
                code = 'INVALID_ARGUMENT',
                details = None,
                message = 'Invalid parameter provided.'
            )
        else:
            return GetImageQrcode400Response(
        )
        """

    def testGetImageQrcode400Response(self):
        """Test GetImageQrcode400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
