# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_hotboard200_response_one_of2 import GetMiscHotboard200ResponseOneOf2

class TestGetMiscHotboard200ResponseOneOf2(unittest.TestCase):
    """GetMiscHotboard200ResponseOneOf2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscHotboard200ResponseOneOf2:
        """Test GetMiscHotboard200ResponseOneOf2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscHotboard200ResponseOneOf2`
        """
        model = GetMiscHotboard200ResponseOneOf2()
        if include_optional:
            return GetMiscHotboard200ResponseOneOf2(
                sources = [
                    'weibo'
                    ]
            )
        else:
            return GetMiscHotboard200ResponseOneOf2(
        )
        """

    def testGetMiscHotboard200ResponseOneOf2(self):
        """Test GetMiscHotboard200ResponseOneOf2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
