# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_image_nsfw413_response import PostImageNsfw413Response

class TestPostImageNsfw413Response(unittest.TestCase):
    """PostImageNsfw413Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostImageNsfw413Response:
        """Test PostImageNsfw413Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostImageNsfw413Response`
        """
        model = PostImageNsfw413Response()
        if include_optional:
            return PostImageNsfw413Response(
                code = 'FILE_TOO_LARGE',
                message = '文件大小超过限制（最大20MB）'
            )
        else:
            return PostImageNsfw413Response(
        )
        """

    def testPostImageNsfw413Response(self):
        """Test PostImageNsfw413Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
