# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_search_engines(self) -> None:
        """Test case for get_search_engines

        获取搜索引擎信息
        """
        pass

    def test_get_sensitive_word_analyze_query(self) -> None:
        """Test case for get_sensitive_word_analyze_query

        查询参数分析
        """
        pass

    def test_post_search_aggregate(self) -> None:
        """Test case for post_search_aggregate

        智能搜索
        """
        pass

    def test_post_sensitive_word_analyze(self) -> None:
        """Test case for post_sensitive_word_analyze

        分析敏感词
        """
        pass

    def test_post_sensitive_word_quick_check(self) -> None:
        """Test case for post_sensitive_word_quick_check

        敏感词检测（快速）
        """
        pass


if __name__ == '__main__':
    unittest.main()
