# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_network_myip200_response import GetNetworkMyip200Response

class TestGetNetworkMyip200Response(unittest.TestCase):
    """GetNetworkMyip200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkMyip200Response:
        """Test GetNetworkMyip200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkMyip200Response`
        """
        model = GetNetworkMyip200Response()
        if include_optional:
            return GetNetworkMyip200Response(
                ip = '117.182.103.101',
                region = '中国 广西 南宁市',
                isp = 'China Mobile Communications Group Co., Ltd.',
                llc = '移动',
                asn = 'AS9808',
                latitude = 22.8111,
                longitude = 108.3168,
                beginip = '117.182.64.0',
                endip = '117.182.127.255',
                district = '青秀区'
            )
        else:
            return GetNetworkMyip200Response(
        )
        """

    def testGetNetworkMyip200Response(self):
        """Test GetNetworkMyip200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
