# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_text_convert400_response import PostTextConvert400Response

class TestPostTextConvert400Response(unittest.TestCase):
    """PostTextConvert400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTextConvert400Response:
        """Test PostTextConvert400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTextConvert400Response`
        """
        model = PostTextConvert400Response()
        if include_optional:
            return PostTextConvert400Response(
                error_code = 'CONVERSION_FAILED',
                error_message = '不支持的源格式: unknown',
                error_details = ''
            )
        else:
            return PostTextConvert400Response(
        )
        """

    def testPostTextConvert400Response(self):
        """Test PostTextConvert400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
