# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather_history200_response_days_inner import GetMiscWeatherHistory200ResponseDaysInner

class TestGetMiscWeatherHistory200ResponseDaysInner(unittest.TestCase):
    """GetMiscWeatherHistory200ResponseDaysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeatherHistory200ResponseDaysInner:
        """Test GetMiscWeatherHistory200ResponseDaysInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeatherHistory200ResponseDaysInner`
        """
        model = GetMiscWeatherHistory200ResponseDaysInner()
        if include_optional:
            return GetMiscWeatherHistory200ResponseDaysInner(
                var_date = '2026-05-01',
                rain = 3.6,
                rained = True,
                temp_max = 24,
                temp_min = 15,
                weather = '小雨'
            )
        else:
            return GetMiscWeatherHistory200ResponseDaysInner(
        )
        """

    def testGetMiscWeatherHistory200ResponseDaysInner(self):
        """Test GetMiscWeatherHistory200ResponseDaysInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
