# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_hotboard200_response_one_of1 import GetMiscHotboard200ResponseOneOf1

class TestGetMiscHotboard200ResponseOneOf1(unittest.TestCase):
    """GetMiscHotboard200ResponseOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscHotboard200ResponseOneOf1:
        """Test GetMiscHotboard200ResponseOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscHotboard200ResponseOneOf1`
        """
        model = GetMiscHotboard200ResponseOneOf1()
        if include_optional:
            return GetMiscHotboard200ResponseOneOf1(
                type = 'weibo',
                keyword = 'AI',
                count = 0,
                results = [
                    uapi.models.get_misc_hotboard_200_response_one_of_1_results_inner.get_misc_hotboard_200_response_oneOf_1_results_inner(
                        title = 'AI技术突破', 
                        hot_value = '999999', 
                        url = 'https://example.com', )
                    ]
            )
        else:
            return GetMiscHotboard200ResponseOneOf1(
        )
        """

    def testGetMiscHotboard200ResponseOneOf1(self):
        """Test GetMiscHotboard200ResponseOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
