# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_web_tomarkdown_async_status200_response import GetWebTomarkdownAsyncStatus200Response

class TestGetWebTomarkdownAsyncStatus200Response(unittest.TestCase):
    """GetWebTomarkdownAsyncStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWebTomarkdownAsyncStatus200Response:
        """Test GetWebTomarkdownAsyncStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWebTomarkdownAsyncStatus200Response`
        """
        model = GetWebTomarkdownAsyncStatus200Response()
        if include_optional:
            return GetWebTomarkdownAsyncStatus200Response(
                task_id = 'a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6',
                status = 'failed',
                url = 'https://example.com',
                progress = 100,
                created_at = '2025-10-13T10:30:45.123456Z',
                message = '任务处理中，请继续轮询',
                started_at = '2025-10-13T10:30:46.000000Z',
                elapsed = 2.5,
                completed_at = '2025-10-13T10:30:48.000000Z',
                duration = 2,
                result = uapi.models.get_web_tomarkdown_async_status_200_response_any_of_2_result.get_web_tomarkdown_async_status_200_response_anyOf_2_result(
                    markdown = '---
title: "示例页面"
author: "作者名"
---

# 示例页面

这是转换后的Markdown内容...', 
                    size = 1234, ),
                error = '网络连接失败: connection timeout'
            )
        else:
            return GetWebTomarkdownAsyncStatus200Response(
        )
        """

    def testGetWebTomarkdownAsyncStatus200Response(self):
        """Test GetWebTomarkdownAsyncStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
