# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.api.web_parse_api import WebParseApi


class TestWebParseApi(unittest.TestCase):
    """WebParseApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebParseApi()

    def tearDown(self) -> None:
        pass

    def test_get_web_tomarkdown_async_status(self) -> None:
        """Test case for get_web_tomarkdown_async_status

        查询网页转换任务状态和结果
        """
        pass

    def test_get_webparse_extractimages(self) -> None:
        """Test case for get_webparse_extractimages

        提取网页中的所有图片
        """
        pass

    def test_get_webparse_metadata(self) -> None:
        """Test case for get_webparse_metadata

        抓取并解析网页的元数据
        """
        pass

    def test_post_web_tomarkdown_async(self) -> None:
        """Test case for post_web_tomarkdown_async

        深度抓取网页转Markdown
        """
        pass


if __name__ == '__main__':
    unittest.main()
