# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_daily_word200_response_words_inner_examples_inner import GetDailyWord200ResponseWordsInnerExamplesInner

class TestGetDailyWord200ResponseWordsInnerExamplesInner(unittest.TestCase):
    """GetDailyWord200ResponseWordsInnerExamplesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDailyWord200ResponseWordsInnerExamplesInner:
        """Test GetDailyWord200ResponseWordsInnerExamplesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDailyWord200ResponseWordsInnerExamplesInner`
        """
        model = GetDailyWord200ResponseWordsInnerExamplesInner()
        if include_optional:
            return GetDailyWord200ResponseWordsInnerExamplesInner(
                text = 'How's the weather?',
                translation = '天气怎么样？'
            )
        else:
            return GetDailyWord200ResponseWordsInnerExamplesInner(
        )
        """

    def testGetDailyWord200ResponseWordsInnerExamplesInner(self):
        """Test GetDailyWord200ResponseWordsInnerExamplesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
