# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_sensitive_word_analyze429_response import PostSensitiveWordAnalyze429Response

class TestPostSensitiveWordAnalyze429Response(unittest.TestCase):
    """PostSensitiveWordAnalyze429Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSensitiveWordAnalyze429Response:
        """Test PostSensitiveWordAnalyze429Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSensitiveWordAnalyze429Response`
        """
        model = PostSensitiveWordAnalyze429Response()
        if include_optional:
            return PostSensitiveWordAnalyze429Response(
                code = 'RATE_LIMIT_EXCEEDED',
                message = '请求频率超限'
            )
        else:
            return PostSensitiveWordAnalyze429Response(
        )
        """

    def testPostSensitiveWordAnalyze429Response(self):
        """Test PostSensitiveWordAnalyze429Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
