# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_game_steam_summary502_response import GetGameSteamSummary502Response

class TestGetGameSteamSummary502Response(unittest.TestCase):
    """GetGameSteamSummary502Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGameSteamSummary502Response:
        """Test GetGameSteamSummary502Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGameSteamSummary502Response`
        """
        model = GetGameSteamSummary502Response()
        if include_optional:
            return GetGameSteamSummary502Response(
                code = 'UPSTREAM_ERROR',
                details = None,
                message = 'Failed to fetch data from Steam API.'
            )
        else:
            return GetGameSteamSummary502Response(
        )
        """

    def testGetGameSteamSummary502Response(self):
        """Test GetGameSteamSummary502Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
