# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_webparse_extractimages200_response import GetWebparseExtractimages200Response

class TestGetWebparseExtractimages200Response(unittest.TestCase):
    """GetWebparseExtractimages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWebparseExtractimages200Response:
        """Test GetWebparseExtractimages200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWebparseExtractimages200Response`
        """
        model = GetWebparseExtractimages200Response()
        if include_optional:
            return GetWebparseExtractimages200Response(
                count = 25,
                images = ["https://example.com/image1.jpg","https://example.com/image2.png"],
                url = 'https://example.com'
            )
        else:
            return GetWebparseExtractimages200Response(
        )
        """

    def testGetWebparseExtractimages200Response(self):
        """Test GetWebparseExtractimages200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
