# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_watermark_producer_code_request import PostWatermarkProducerCodeRequest

class TestPostWatermarkProducerCodeRequest(unittest.TestCase):
    """PostWatermarkProducerCodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWatermarkProducerCodeRequest:
        """Test PostWatermarkProducerCodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWatermarkProducerCodeRequest`
        """
        model = PostWatermarkProducerCodeRequest()
        if include_optional:
            return PostWatermarkProducerCodeRequest(
                binding = 'phone',
                code = '',
                identifier = '13800138000',
                model_code = '0001',
                service_type = 'generation',
                subject_type = 'person'
            )
        else:
            return PostWatermarkProducerCodeRequest(
        )
        """

    def testPostWatermarkProducerCodeRequest(self):
        """Test PostWatermarkProducerCodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
