# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_watermark_label200_response import PostWatermarkLabel200Response

class TestPostWatermarkLabel200Response(unittest.TestCase):
    """PostWatermarkLabel200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWatermarkLabel200Response:
        """Test PostWatermarkLabel200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWatermarkLabel200Response`
        """
        model = PostWatermarkLabel200Response()
        if include_optional:
            return PostWatermarkLabel200Response(
                applied = ["explicit","metadata"],
                capacity_chars = 56,
                content_producer = '',
                format = 'jpeg',
                image_base64 = '',
                image_name = '',
                watermark_payload = ''
            )
        else:
            return PostWatermarkLabel200Response(
        )
        """

    def testPostWatermarkLabel200Response(self):
        """Test PostWatermarkLabel200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
