# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_life_indices_exercise import GetMiscWeather200ResponseLifeIndicesExercise

class TestGetMiscWeather200ResponseLifeIndicesExercise(unittest.TestCase):
    """GetMiscWeather200ResponseLifeIndicesExercise unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseLifeIndicesExercise:
        """Test GetMiscWeather200ResponseLifeIndicesExercise
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseLifeIndicesExercise`
        """
        model = GetMiscWeather200ResponseLifeIndicesExercise()
        if include_optional:
            return GetMiscWeather200ResponseLifeIndicesExercise(
                level = '适宜',
                brief = '较好',
                advice = '天气适合运动'
            )
        else:
            return GetMiscWeather200ResponseLifeIndicesExercise(
        )
        """

    def testGetMiscWeather200ResponseLifeIndicesExercise(self):
        """Test GetMiscWeather200ResponseLifeIndicesExercise"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
