# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_tracking_query200_response import GetMiscTrackingQuery200Response

class TestGetMiscTrackingQuery200Response(unittest.TestCase):
    """GetMiscTrackingQuery200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscTrackingQuery200Response:
        """Test GetMiscTrackingQuery200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscTrackingQuery200Response`
        """
        model = GetMiscTrackingQuery200Response()
        if include_optional:
            return GetMiscTrackingQuery200Response(
                code = 'SUCCESS',
                message = '操作成功',
                data = uapi.models.get_misc_tracking_query_200_response_data.get_misc_tracking_query_200_response_data(
                    tracking_number = 'YT1234567890123', 
                    carrier_code = 'yuantong', 
                    carrier_name = '圆通速递', 
                    track_count = 3, 
                    tracks = [
                        uapi.models.get_misc_tracking_query_200_response_data_tracks_inner.get_misc_tracking_query_200_response_data_tracks_inner(
                            time = '2025-10-27 15:30:00', 
                            context = '快件已签收，感谢使用圆通速递', )
                        ], )
            )
        else:
            return GetMiscTrackingQuery200Response(
        )
        """

    def testGetMiscTrackingQuery200Response(self):
        """Test GetMiscTrackingQuery200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
