# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_holiday_calendar200_response_nearby_previous_inner import GetMiscHolidayCalendar200ResponseNearbyPreviousInner

class TestGetMiscHolidayCalendar200ResponseNearbyPreviousInner(unittest.TestCase):
    """GetMiscHolidayCalendar200ResponseNearbyPreviousInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscHolidayCalendar200ResponseNearbyPreviousInner:
        """Test GetMiscHolidayCalendar200ResponseNearbyPreviousInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscHolidayCalendar200ResponseNearbyPreviousInner`
        """
        model = GetMiscHolidayCalendar200ResponseNearbyPreviousInner()
        if include_optional:
            return GetMiscHolidayCalendar200ResponseNearbyPreviousInner(
                var_date = '2025-09-28',
                events = [
                    uapi.models.get_misc_holiday_calendar_200_response_nearby_previous_inner_events_inner.get_misc_holiday_calendar_200_response_nearby_previous_inner_events_inner(
                        date = '2025-09-28', 
                        name = '国庆中秋', 
                        type = 'legal_workday_adjust', 
                        is_workday = True, )
                    ]
            )
        else:
            return GetMiscHolidayCalendar200ResponseNearbyPreviousInner(
        )
        """

    def testGetMiscHolidayCalendar200ResponseNearbyPreviousInner(self):
        """Test GetMiscHolidayCalendar200ResponseNearbyPreviousInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
