# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_timestamp200_response import GetMiscTimestamp200Response

class TestGetMiscTimestamp200Response(unittest.TestCase):
    """GetMiscTimestamp200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscTimestamp200Response:
        """Test GetMiscTimestamp200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscTimestamp200Response`
        """
        model = GetMiscTimestamp200Response()
        if include_optional:
            return GetMiscTimestamp200Response(
                datetime_local = '2023-01-01 08:00:00',
                datetime_utc = '2023-01-01 00:00:00',
                input = '1672531200',
                type = '秒',
                unix_timestamp = 1672531200
            )
        else:
            return GetMiscTimestamp200Response(
        )
        """

    def testGetMiscTimestamp200Response(self):
        """Test GetMiscTimestamp200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
