# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_ai_translate_languages200_response import GetAiTranslateLanguages200Response

class TestGetAiTranslateLanguages200Response(unittest.TestCase):
    """GetAiTranslateLanguages200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetAiTranslateLanguages200Response:
        """Test GetAiTranslateLanguages200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetAiTranslateLanguages200Response`
        """
        model = GetAiTranslateLanguages200Response()
        if include_optional:
            return GetAiTranslateLanguages200Response(
                code = 200,
                message = 'Supported languages retrieved successfully',
                data = uapi.models.get_ai_translate_languages_200_response_data.get_ai_translate_languages_200_response_data(
                    languages = [
                        uapi.models.get_ai_translate_languages_200_response_data_languages_inner.get_ai_translate_languages_200_response_data_languages_inner(
                            code = 'zh-CHS', 
                            name = 'Chinese (Simplified)', 
                            native = '中文(简体)', )
                        ], 
                    styles = [
                        uapi.models.get_ai_translate_languages_200_response_data_styles_inner.get_ai_translate_languages_200_response_data_styles_inner(
                            code = 'professional', 
                            name = 'Professional', 
                            description = 'Formal, business-appropriate style', )
                        ], 
                    contexts = [
                        uapi.models.get_ai_translate_languages_200_response_data_contexts_inner.get_ai_translate_languages_200_response_data_contexts_inner(
                            code = 'business', 
                            name = 'Business', 
                            description = 'Business and corporate content', )
                        ], ),
                performance = uapi.models.get_ai_translate_languages_200_response_performance.get_ai_translate_languages_200_response_performance(
                    fast_mode_available = True, 
                    batch_translation_available = True, 
                    max_text_length = 10000, 
                    max_batch_size = 50, 
                    typical_response_time_ms = uapi.models.get_ai_translate_languages_200_response_performance_typical_response_time_ms.get_ai_translate_languages_200_response_performance_typical_response_time_ms(
                        fast_mode = 800, 
                        normal_mode = 2000, ), )
            )
        else:
            return GetAiTranslateLanguages200Response(
        )
        """

    def testGetAiTranslateLanguages200Response(self):
        """Test GetAiTranslateLanguages200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
