# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_github_user200_response_activity_contribution_calendar_weeks_inner_contribution_days_inner import GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner

class TestGetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner(unittest.TestCase):
    """GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner:
        """Test GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner`
        """
        model = GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner()
        if include_optional:
            return GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner(
                var_date = '2026-04-07',
                contribution_count = 1,
                color = '#40c463',
                weekday = 2
            )
        else:
            return GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner(
        )
        """

    def testGetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner(self):
        """Test GetGithubUser200ResponseActivityContributionCalendarWeeksInnerContributionDaysInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
