# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_holiday_calendar200_response_summary import GetMiscHolidayCalendar200ResponseSummary

class TestGetMiscHolidayCalendar200ResponseSummary(unittest.TestCase):
    """GetMiscHolidayCalendar200ResponseSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscHolidayCalendar200ResponseSummary:
        """Test GetMiscHolidayCalendar200ResponseSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscHolidayCalendar200ResponseSummary`
        """
        model = GetMiscHolidayCalendar200ResponseSummary()
        if include_optional:
            return GetMiscHolidayCalendar200ResponseSummary(
                total_days = 1,
                weekend_days = 0,
                workdays = 0,
                rest_days = 1,
                holiday_events = 1,
                legal_rest_days = 1,
                legal_workdays = 0
            )
        else:
            return GetMiscHolidayCalendar200ResponseSummary(
        )
        """

    def testGetMiscHolidayCalendar200ResponseSummary(self):
        """Test GetMiscHolidayCalendar200ResponseSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
