# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.daily_recommend_moment_scene import DailyRecommendMomentScene

class TestDailyRecommendMomentScene(unittest.TestCase):
    """DailyRecommendMomentScene unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DailyRecommendMomentScene:
        """Test DailyRecommendMomentScene
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DailyRecommendMomentScene`
        """
        model = DailyRecommendMomentScene()
        if include_optional:
            return DailyRecommendMomentScene(
                description = '偏思考、回味、轻情绪化的语料',
                key = 'night',
                name = '夜晚'
            )
        else:
            return DailyRecommendMomentScene(
        )
        """

    def testDailyRecommendMomentScene(self):
        """Test DailyRecommendMomentScene"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
