# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_clipzy_store_request import PostClipzyStoreRequest

class TestPostClipzyStoreRequest(unittest.TestCase):
    """PostClipzyStoreRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostClipzyStoreRequest:
        """Test PostClipzyStoreRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostClipzyStoreRequest`
        """
        model = PostClipzyStoreRequest()
        if include_optional:
            return PostClipzyStoreRequest(
                compressed_data = 'PIZQqgLgUgNg6gEQEYAUCuBrA7gSQBoDMAiigPakCOAYgQIYBKEA7AFbABqAEiAJYBmAYSJUAznHbsAcgBMBAFQDSAegCcALz4BZKHDwql9DADtOCqvQCCATQowAWhgVgYAUwBMAFgC8QA==',
                ttl = 3600
            )
        else:
            return PostClipzyStoreRequest(
                compressed_data = 'PIZQqgLgUgNg6gEQEYAUCuBrA7gSQBoDMAiigPakCOAYgQIYBKEA7AFbABqAEiAJYBmAYSJUAznHbsAcgBMBAFQDSAegCcALz4BZKHDwql9DADtOCqvQCCATQowAWhgVgYAUwBMAFgC8QA==',
        )
        """

    def testPostClipzyStoreRequest(self):
        """Test PostClipzyStoreRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
