# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_image_ocr400_response_one_of1 import PostImageOcr400ResponseOneOf1

class TestPostImageOcr400ResponseOneOf1(unittest.TestCase):
    """PostImageOcr400ResponseOneOf1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostImageOcr400ResponseOneOf1:
        """Test PostImageOcr400ResponseOneOf1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostImageOcr400ResponseOneOf1`
        """
        model = PostImageOcr400ResponseOneOf1()
        if include_optional:
            return PostImageOcr400ResponseOneOf1(
                code = 'INVALID_PARAMETER',
                message = 'file、url、image_base64 请勿同时提交，只能选择一种方式'
            )
        else:
            return PostImageOcr400ResponseOneOf1(
        )
        """

    def testPostImageOcr400ResponseOneOf1(self):
        """Test PostImageOcr400ResponseOneOf1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
