# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_web_tomarkdown_async_status404_response import GetWebTomarkdownAsyncStatus404Response

class TestGetWebTomarkdownAsyncStatus404Response(unittest.TestCase):
    """GetWebTomarkdownAsyncStatus404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWebTomarkdownAsyncStatus404Response:
        """Test GetWebTomarkdownAsyncStatus404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWebTomarkdownAsyncStatus404Response`
        """
        model = GetWebTomarkdownAsyncStatus404Response()
        if include_optional:
            return GetWebTomarkdownAsyncStatus404Response(
                error = '任务不存在',
                message = '未找到指定的task_id，任务可能已过期（30分钟TTL）',
                code = 404
            )
        else:
            return GetWebTomarkdownAsyncStatus404Response(
        )
        """

    def testGetWebTomarkdownAsyncStatus404Response(self):
        """Test GetWebTomarkdownAsyncStatus404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
