# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_social_bilibili_replies200_response import GetSocialBilibiliReplies200Response

class TestGetSocialBilibiliReplies200Response(unittest.TestCase):
    """GetSocialBilibiliReplies200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSocialBilibiliReplies200Response:
        """Test GetSocialBilibiliReplies200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSocialBilibiliReplies200Response`
        """
        model = GetSocialBilibiliReplies200Response()
        if include_optional:
            return GetSocialBilibiliReplies200Response(
                page = uapi.models.get_social_bilibili_replies_200_response_page.get_social_bilibili_replies_200_response_page(
                    num = 1, 
                    size = 5, 
                    count = 81682, 
                    acount = 123456, ),
                hots = [
                    None
                    ],
                replies = [
                    uapi.models.get_social_bilibili_replies_200_response_replies_inner.get_social_bilibili_replies_200_response_replies_inner(
                        rpid = 4189337397, 
                        oid = 1706416465, 
                        mid = 12345678, 
                        root = 4189337300, 
                        parent = 4189337300, 
                        count = 520, 
                        ctime = 1579532400, 
                        like = 1314, 
                        member = uapi.models.get_social_bilibili_replies_200_response_replies_inner_member.get_social_bilibili_replies_200_response_replies_inner_member(
                            uname = '评论区大神', 
                            sex = '男', 
                            avatar = 'http://i0.hdslb.com/bfs/face/....jpg', 
                            level_info = uapi.models.get_social_bilibili_replies_200_response_replies_inner_member_level_info.get_social_bilibili_replies_200_response_replies_inner_member_level_info(
                                current_level = 6, ), ), 
                        content = uapi.models.get_social_bilibili_replies_200_response_replies_inner_content.get_social_bilibili_replies_200_response_replies_inner_content(
                            message = '十年B站无人问，一朝发现宝藏歌。', ), 
                        replies = [
                            None
                            ], )
                    ]
            )
        else:
            return GetSocialBilibiliReplies200Response(
        )
        """

    def testGetSocialBilibiliReplies200Response(self):
        """Test GetSocialBilibiliReplies200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
