# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_ai_translate_request import PostAiTranslateRequest

class TestPostAiTranslateRequest(unittest.TestCase):
    """PostAiTranslateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAiTranslateRequest:
        """Test PostAiTranslateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAiTranslateRequest`
        """
        model = PostAiTranslateRequest()
        if include_optional:
            return PostAiTranslateRequest(
                text = 'Hello, how are you today?',
                texts = [
                    ''
                    ],
                source_lang = 'en',
                style = 'professional',
                context = 'general',
                preserve_format = True,
                fast_mode = True,
                max_concurrency = 3
            )
        else:
            return PostAiTranslateRequest(
        )
        """

    def testPostAiTranslateRequest(self):
        """Test PostAiTranslateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
