# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_network_pingmyip200_response import GetNetworkPingmyip200Response

class TestGetNetworkPingmyip200Response(unittest.TestCase):
    """GetNetworkPingmyip200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkPingmyip200Response:
        """Test GetNetworkPingmyip200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkPingmyip200Response`
        """
        model = GetNetworkPingmyip200Response()
        if include_optional:
            return GetNetworkPingmyip200Response(
                avg = 35.4,
                code = 200,
                host = '123.123.123.123',
                ip = '123.123.123.123',
                location = '中国 北京',
                max = 40.1,
                min = 32.8
            )
        else:
            return GetNetworkPingmyip200Response(
        )
        """

    def testGetNetworkPingmyip200Response(self):
        """Test GetNetworkPingmyip200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
