# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_text_base64_encode_request import PostTextBase64EncodeRequest

class TestPostTextBase64EncodeRequest(unittest.TestCase):
    """PostTextBase64EncodeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTextBase64EncodeRequest:
        """Test PostTextBase64EncodeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTextBase64EncodeRequest`
        """
        model = PostTextBase64EncodeRequest()
        if include_optional:
            return PostTextBase64EncodeRequest(
                text = 'hello world'
            )
        else:
            return PostTextBase64EncodeRequest(
                text = 'hello world',
        )
        """

    def testPostTextBase64EncodeRequest(self):
        """Test PostTextBase64EncodeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
