# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_social_qq_groupinfo500_response import GetSocialQqGroupinfo500Response

class TestGetSocialQqGroupinfo500Response(unittest.TestCase):
    """GetSocialQqGroupinfo500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSocialQqGroupinfo500Response:
        """Test GetSocialQqGroupinfo500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSocialQqGroupinfo500Response`
        """
        model = GetSocialQqGroupinfo500Response()
        if include_optional:
            return GetSocialQqGroupinfo500Response(
                code = 'INTERNAL_ERROR',
                details = None,
                message = 'Failed to retrieve QQ group info.'
            )
        else:
            return GetSocialQqGroupinfo500Response(
        )
        """

    def testGetSocialQqGroupinfo500Response(self):
        """Test GetSocialQqGroupinfo500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
