# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_life_indices_air_conditioner import GetMiscWeather200ResponseLifeIndicesAirConditioner

class TestGetMiscWeather200ResponseLifeIndicesAirConditioner(unittest.TestCase):
    """GetMiscWeather200ResponseLifeIndicesAirConditioner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseLifeIndicesAirConditioner:
        """Test GetMiscWeather200ResponseLifeIndicesAirConditioner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseLifeIndicesAirConditioner`
        """
        model = GetMiscWeather200ResponseLifeIndicesAirConditioner()
        if include_optional:
            return GetMiscWeather200ResponseLifeIndicesAirConditioner(
                level = '建议制热',
                brief = '寒冷',
                advice = '建议开启空调制热'
            )
        else:
            return GetMiscWeather200ResponseLifeIndicesAirConditioner(
        )
        """

    def testGetMiscWeather200ResponseLifeIndicesAirConditioner(self):
        """Test GetMiscWeather200ResponseLifeIndicesAirConditioner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
