# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_network_dns400_response import GetNetworkDns400Response

class TestGetNetworkDns400Response(unittest.TestCase):
    """GetNetworkDns400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkDns400Response:
        """Test GetNetworkDns400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkDns400Response`
        """
        model = GetNetworkDns400Response()
        if include_optional:
            return GetNetworkDns400Response(
                code = 'INVALID_ARGUMENT',
                details = None,
                message = 'Missing or invalid 'domain' parameter.'
            )
        else:
            return GetNetworkDns400Response(
        )
        """

    def testGetNetworkDns400Response(self):
        """Test GetNetworkDns400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
