# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_social_qq_userinfo404_response import GetSocialQqUserinfo404Response

class TestGetSocialQqUserinfo404Response(unittest.TestCase):
    """GetSocialQqUserinfo404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSocialQqUserinfo404Response:
        """Test GetSocialQqUserinfo404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSocialQqUserinfo404Response`
        """
        model = GetSocialQqUserinfo404Response()
        if include_optional:
            return GetSocialQqUserinfo404Response(
                code = 'NOT_FOUND',
                details = None,
                message = 'Failed to retrieve QQ user info, user may not exist.'
            )
        else:
            return GetSocialQqUserinfo404Response(
        )
        """

    def testGetSocialQqUserinfo404Response(self):
        """Test GetSocialQqUserinfo404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
