# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_game_steam_summary401_response import GetGameSteamSummary401Response

class TestGetGameSteamSummary401Response(unittest.TestCase):
    """GetGameSteamSummary401Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetGameSteamSummary401Response:
        """Test GetGameSteamSummary401Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetGameSteamSummary401Response`
        """
        model = GetGameSteamSummary401Response()
        if include_optional:
            return GetGameSteamSummary401Response(
                code = 'UNAUTHENTICATED',
                details = None,
                message = 'Missing or invalid API Key.'
            )
        else:
            return GetGameSteamSummary401Response(
        )
        """

    def testGetGameSteamSummary401Response(self):
        """Test GetGameSteamSummary401Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
