# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_ai_translate200_response_data_explanation import PostAiTranslate200ResponseDataExplanation

class TestPostAiTranslate200ResponseDataExplanation(unittest.TestCase):
    """PostAiTranslate200ResponseDataExplanation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAiTranslate200ResponseDataExplanation:
        """Test PostAiTranslate200ResponseDataExplanation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAiTranslate200ResponseDataExplanation`
        """
        model = PostAiTranslate200ResponseDataExplanation()
        if include_optional:
            return PostAiTranslate200ResponseDataExplanation(
                key_phrases = [
                    None
                    ],
                cultural_notes = [
                    ''
                    ],
                grammar_notes = [
                    ''
                    ]
            )
        else:
            return PostAiTranslate200ResponseDataExplanation(
        )
        """

    def testPostAiTranslate200ResponseDataExplanation(self):
        """Test PostAiTranslate200ResponseDataExplanation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
