# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_image_ocr415_response import PostImageOcr415Response

class TestPostImageOcr415Response(unittest.TestCase):
    """PostImageOcr415Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostImageOcr415Response:
        """Test PostImageOcr415Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostImageOcr415Response`
        """
        model = PostImageOcr415Response()
        if include_optional:
            return PostImageOcr415Response(
                code = 'UNSUPPORTED_MEDIA_TYPE',
                message = '当前只接受常见图片格式'
            )
        else:
            return PostImageOcr415Response(
        )
        """

    def testPostImageOcr415Response(self):
        """Test PostImageOcr415Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
