# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_image_motou400_response import GetImageMotou400Response

class TestGetImageMotou400Response(unittest.TestCase):
    """GetImageMotou400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImageMotou400Response:
        """Test GetImageMotou400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImageMotou400Response`
        """
        model = GetImageMotou400Response()
        if include_optional:
            return GetImageMotou400Response(
                error = 'QQ number is required'
            )
        else:
            return GetImageMotou400Response(
        )
        """

    def testGetImageMotou400Response(self):
        """Test GetImageMotou400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
