# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_text_markdown_to_html200_response import PostTextMarkdownToHtml200Response

class TestPostTextMarkdownToHtml200Response(unittest.TestCase):
    """PostTextMarkdownToHtml200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTextMarkdownToHtml200Response:
        """Test PostTextMarkdownToHtml200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTextMarkdownToHtml200Response`
        """
        model = PostTextMarkdownToHtml200Response()
        if include_optional:
            return PostTextMarkdownToHtml200Response(
                data = uapi.models.post_text_markdown_to_html_200_response_data.post_text_markdown_to_html_200_response_data(
                    html = '<style>...</style><div class="uapi-markdown"><h1 id="coffee">咖啡</h1><p>...</p></div>', )
            )
        else:
            return PostTextMarkdownToHtml200Response(
        )
        """

    def testPostTextMarkdownToHtml200Response(self):
        """Test PostTextMarkdownToHtml200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
