# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.api.network_api import NetworkApi


class TestNetworkApi(unittest.TestCase):
    """NetworkApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NetworkApi()

    def tearDown(self) -> None:
        pass

    def test_get_network_dns(self) -> None:
        """Test case for get_network_dns

        执行DNS解析查询
        """
        pass

    def test_get_network_icp(self) -> None:
        """Test case for get_network_icp

        查询域名ICP备案信息
        """
        pass

    def test_get_network_ipinfo(self) -> None:
        """Test case for get_network_ipinfo

        查询指定IP或域名的归属信息
        """
        pass

    def test_get_network_myip(self) -> None:
        """Test case for get_network_myip

        获取你的公网IP及归属信息
        """
        pass

    def test_get_network_ping(self) -> None:
        """Test case for get_network_ping

        从服务器Ping指定主机
        """
        pass

    def test_get_network_pingmyip(self) -> None:
        """Test case for get_network_pingmyip

        从服务器Ping你的客户端IP
        """
        pass

    def test_get_network_portscan(self) -> None:
        """Test case for get_network_portscan

        扫描远程主机的指定端口
        """
        pass

    def test_get_network_urlstatus(self) -> None:
        """Test case for get_network_urlstatus

        检查URL的可访问性状态
        """
        pass

    def test_get_network_whois(self) -> None:
        """Test case for get_network_whois

        查询域名的WHOIS注册信息
        """
        pass

    def test_get_network_wxdomain(self) -> None:
        """Test case for get_network_wxdomain

        检查域名在微信中的访问状态
        """
        pass


if __name__ == '__main__':
    unittest.main()
