# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_network_whois200_response_one_of import GetNetworkWhois200ResponseOneOf

class TestGetNetworkWhois200ResponseOneOf(unittest.TestCase):
    """GetNetworkWhois200ResponseOneOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetNetworkWhois200ResponseOneOf:
        """Test GetNetworkWhois200ResponseOneOf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetNetworkWhois200ResponseOneOf`
        """
        model = GetNetworkWhois200ResponseOneOf()
        if include_optional:
            return GetNetworkWhois200ResponseOneOf(
                code = 200,
                whois = 'Domain Name: GOOGLE.COM
Registry Domain ID: 2138514_DOMAIN_COM-VRSN
Registrar WHOIS Server: whois.markmonitor.com
...'
            )
        else:
            return GetNetworkWhois200ResponseOneOf(
        )
        """

    def testGetNetworkWhois200ResponseOneOf(self):
        """Test GetNetworkWhois200ResponseOneOf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
