# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_phoneinfo500_response import GetMiscPhoneinfo500Response

class TestGetMiscPhoneinfo500Response(unittest.TestCase):
    """GetMiscPhoneinfo500Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscPhoneinfo500Response:
        """Test GetMiscPhoneinfo500Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscPhoneinfo500Response`
        """
        model = GetMiscPhoneinfo500Response()
        if include_optional:
            return GetMiscPhoneinfo500Response(
                code = 'INTERNAL_SERVER_ERROR',
                details = None,
                message = 'Failed to query phone information.'
            )
        else:
            return GetMiscPhoneinfo500Response(
        )
        """

    def testGetMiscPhoneinfo500Response(self):
        """Test GetMiscPhoneinfo500Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
