# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_dictionary_lookup200_response_entry_examples_inner import GetDictionaryLookup200ResponseEntryExamplesInner

class TestGetDictionaryLookup200ResponseEntryExamplesInner(unittest.TestCase):
    """GetDictionaryLookup200ResponseEntryExamplesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDictionaryLookup200ResponseEntryExamplesInner:
        """Test GetDictionaryLookup200ResponseEntryExamplesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDictionaryLookup200ResponseEntryExamplesInner`
        """
        model = GetDictionaryLookup200ResponseEntryExamplesInner()
        if include_optional:
            return GetDictionaryLookup200ResponseEntryExamplesInner(
                source = 'Did you get your mother a present?',
                translation = '给你母亲买礼物了吗？'
            )
        else:
            return GetDictionaryLookup200ResponseEntryExamplesInner(
        )
        """

    def testGetDictionaryLookup200ResponseEntryExamplesInner(self):
        """Test GetDictionaryLookup200ResponseEntryExamplesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
