# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_tracking_carriers200_response import GetMiscTrackingCarriers200Response

class TestGetMiscTrackingCarriers200Response(unittest.TestCase):
    """GetMiscTrackingCarriers200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscTrackingCarriers200Response:
        """Test GetMiscTrackingCarriers200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscTrackingCarriers200Response`
        """
        model = GetMiscTrackingCarriers200Response()
        if include_optional:
            return GetMiscTrackingCarriers200Response(
                code = 'SUCCESS',
                message = '操作成功',
                data = uapi.models.get_misc_tracking_carriers_200_response_data.get_misc_tracking_carriers_200_response_data(
                    total = 60, 
                    carriers = [
                        uapi.models.get_misc_tracking_carriers_200_response_data_carriers_inner.get_misc_tracking_carriers_200_response_data_carriers_inner(
                            code = 'zhongtong', 
                            name = '中通快递', )
                        ], )
            )
        else:
            return GetMiscTrackingCarriers200Response(
        )
        """

    def testGetMiscTrackingCarriers200Response(self):
        """Test GetMiscTrackingCarriers200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
