# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_daily_word200_response_words_inner import GetDailyWord200ResponseWordsInner

class TestGetDailyWord200ResponseWordsInner(unittest.TestCase):
    """GetDailyWord200ResponseWordsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDailyWord200ResponseWordsInner:
        """Test GetDailyWord200ResponseWordsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDailyWord200ResponseWordsInner`
        """
        model = GetDailyWord200ResponseWordsInner()
        if include_optional:
            return GetDailyWord200ResponseWordsInner(
                definition = 'n. the atmospheric conditions at a place and time',
                examples = [
                    uapi.models.get_daily_word_200_response_words_inner_examples_inner.get_daily_word_200_response_words_inner_examples_inner(
                        text = 'How's the weather?', 
                        translation = '天气怎么样？', )
                    ],
                phonetic = '/ˈweðər/',
                word = 'weather'
            )
        else:
            return GetDailyWord200ResponseWordsInner(
        )
        """

    def testGetDailyWord200ResponseWordsInner(self):
        """Test GetDailyWord200ResponseWordsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
