# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_search_aggregate400_response import PostSearchAggregate400Response

class TestPostSearchAggregate400Response(unittest.TestCase):
    """PostSearchAggregate400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSearchAggregate400Response:
        """Test PostSearchAggregate400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSearchAggregate400Response`
        """
        model = PostSearchAggregate400Response()
        if include_optional:
            return PostSearchAggregate400Response(
                code = 'INVALID_REQUEST',
                message = '请求参数格式错误',
                timestamp = '2024-01-15T10:30Z'
            )
        else:
            return PostSearchAggregate400Response(
        )
        """

    def testPostSearchAggregate400Response(self):
        """Test PostSearchAggregate400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
