# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_tracking_query200_response_tracks_inner import GetMiscTrackingQuery200ResponseTracksInner

class TestGetMiscTrackingQuery200ResponseTracksInner(unittest.TestCase):
    """GetMiscTrackingQuery200ResponseTracksInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscTrackingQuery200ResponseTracksInner:
        """Test GetMiscTrackingQuery200ResponseTracksInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscTrackingQuery200ResponseTracksInner`
        """
        model = GetMiscTrackingQuery200ResponseTracksInner()
        if include_optional:
            return GetMiscTrackingQuery200ResponseTracksInner(
                time = '2025-10-27 15:30:00',
                context = '快件已签收，感谢使用圆通速递'
            )
        else:
            return GetMiscTrackingQuery200ResponseTracksInner(
        )
        """

    def testGetMiscTrackingQuery200ResponseTracksInner(self):
        """Test GetMiscTrackingQuery200ResponseTracksInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
