# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_air_pollutants import GetMiscWeather200ResponseAirPollutants

class TestGetMiscWeather200ResponseAirPollutants(unittest.TestCase):
    """GetMiscWeather200ResponseAirPollutants unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseAirPollutants:
        """Test GetMiscWeather200ResponseAirPollutants
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseAirPollutants`
        """
        model = GetMiscWeather200ResponseAirPollutants()
        if include_optional:
            return GetMiscWeather200ResponseAirPollutants(
                pm25 = 33,
                pm10 = 69,
                o3 = 91,
                no2 = 13,
                so2 = 7,
                co = 0.4
            )
        else:
            return GetMiscWeather200ResponseAirPollutants(
        )
        """

    def testGetMiscWeather200ResponseAirPollutants(self):
        """Test GetMiscWeather200ResponseAirPollutants"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
