# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_webparse_metadata200_response import GetWebparseMetadata200Response

class TestGetWebparseMetadata200Response(unittest.TestCase):
    """GetWebparseMetadata200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetWebparseMetadata200Response:
        """Test GetWebparseMetadata200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetWebparseMetadata200Response`
        """
        model = GetWebparseMetadata200Response()
        if include_optional:
            return GetWebparseMetadata200Response(
                page_url = 'https://www.bilibili.com',
                title = '哔哩哔哩 (゜-゜)つロ 干杯~-bilibili',
                description = 'bilibili是国内知名的视频弹幕网站，这里有及时的动漫新番，活跃的ACG氛围，有创意的Up主。大家可以在这里找到许多欢乐。',
                keywords = ["B站","弹幕","视频"],
                favicon_url = 'https://i0.hdslb.com/bfs/static/jinkela/long/images/512.png',
                language = 'zh-CN',
                author = '',
                published_time = '',
                canonical_url = 'https://www.bilibili.com/',
                generator = '',
                open_graph = {}
            )
        else:
            return GetWebparseMetadata200Response(
        )
        """

    def testGetWebparseMetadata200Response(self):
        """Test GetWebparseMetadata200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
