# coding: utf-8

"""
    UAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_image_bing_daily_history400_response import GetImageBingDailyHistory400Response

class TestGetImageBingDailyHistory400Response(unittest.TestCase):
    """GetImageBingDailyHistory400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetImageBingDailyHistory400Response:
        """Test GetImageBingDailyHistory400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetImageBingDailyHistory400Response`
        """
        model = GetImageBingDailyHistory400Response()
        if include_optional:
            return GetImageBingDailyHistory400Response(
                error = 'page_size 必须是正整数'
            )
        else:
            return GetImageBingDailyHistory400Response(
        )
        """

    def testGetImageBingDailyHistory400Response(self):
        """Test GetImageBingDailyHistory400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
