# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_sensitive_word_analyze_request import PostSensitiveWordAnalyzeRequest

class TestPostSensitiveWordAnalyzeRequest(unittest.TestCase):
    """PostSensitiveWordAnalyzeRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSensitiveWordAnalyzeRequest:
        """Test PostSensitiveWordAnalyzeRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSensitiveWordAnalyzeRequest`
        """
        model = PostSensitiveWordAnalyzeRequest()
        if include_optional:
            return PostSensitiveWordAnalyzeRequest(
                keywords = ["喵","cnm","ccb"]
            )
        else:
            return PostSensitiveWordAnalyzeRequest(
                keywords = ["喵","cnm","ccb"],
        )
        """

    def testPostSensitiveWordAnalyzeRequest(self):
        """Test PostSensitiveWordAnalyzeRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
