# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_holiday_calendar200_response_data_query import GetMiscHolidayCalendar200ResponseDataQuery

class TestGetMiscHolidayCalendar200ResponseDataQuery(unittest.TestCase):
    """GetMiscHolidayCalendar200ResponseDataQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscHolidayCalendar200ResponseDataQuery:
        """Test GetMiscHolidayCalendar200ResponseDataQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscHolidayCalendar200ResponseDataQuery`
        """
        model = GetMiscHolidayCalendar200ResponseDataQuery()
        if include_optional:
            return GetMiscHolidayCalendar200ResponseDataQuery(
                var_date = '2025-10-01',
                month = '2025-10',
                year = '2026',
                timezone = 'Asia/Shanghai',
                holiday_type = 'all',
                include_nearby = True,
                nearby_limit = 7
            )
        else:
            return GetMiscHolidayCalendar200ResponseDataQuery(
        )
        """

    def testGetMiscHolidayCalendar200ResponseDataQuery(self):
        """Test GetMiscHolidayCalendar200ResponseDataQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
