# coding: utf-8

"""
    UAPI OpenAPI

    Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.random import Random

class TestRandom(unittest.TestCase):
    """Random unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Random:
        """Test Random
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Random`
        """
        model = Random()
        if include_optional:
            return Random(
                author = '绿川幸',
                authorinfo = uapi.models.______random__authorinfo.______random__authorinfo(
                    bio = '代表作包括《夏目友人帐》。', 
                    description = '漫画作者', 
                    id = 'natsume', 
                    link = 'https://example.com/author/natsume', 
                    name = '绿川幸', ),
                category = '动画',
                content = '无论多么微小的邂逅，都必定有着某种意义。',
                content_length = 21,
                corpus = 'sentences-bundle',
                created_at = '1675500151',
                matched_tags = ["治愈","温柔"],
                source = '夏目友人帐',
                uuid = 'dfs-5d3627b262f01db19ddf29d0c8d94828'
            )
        else:
            return Random(
        )
        """

    def testRandom(self):
        """Test Random"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
