# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_web_tomarkdown_async202_response import PostWebTomarkdownAsync202Response

class TestPostWebTomarkdownAsync202Response(unittest.TestCase):
    """PostWebTomarkdownAsync202Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostWebTomarkdownAsync202Response:
        """Test PostWebTomarkdownAsync202Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostWebTomarkdownAsync202Response`
        """
        model = PostWebTomarkdownAsync202Response()
        if include_optional:
            return PostWebTomarkdownAsync202Response(
                task_id = 'a1b2c3d4-e5f6-47a8-b9c0-d1e2f3a4b5c6',
                status = 'pending',
                url = 'https://example.com',
                created_at = '2025-10-13T10:30:45.123456Z',
                message = '任务已提交，请使用task_id查询结果'
            )
        else:
            return PostWebTomarkdownAsync202Response(
        )
        """

    def testPostWebTomarkdownAsync202Response(self):
        """Test PostWebTomarkdownAsync202Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
