# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_life_indices_uv import GetMiscWeather200ResponseLifeIndicesUv

class TestGetMiscWeather200ResponseLifeIndicesUv(unittest.TestCase):
    """GetMiscWeather200ResponseLifeIndicesUv unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseLifeIndicesUv:
        """Test GetMiscWeather200ResponseLifeIndicesUv
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseLifeIndicesUv`
        """
        model = GetMiscWeather200ResponseLifeIndicesUv()
        if include_optional:
            return GetMiscWeather200ResponseLifeIndicesUv(
                level = '高',
                brief = '较强',
                advice = '紫外线较强，减少10-14点户外活动，涂抹SPF30+防晒霜，戴帽子和墨镜'
            )
        else:
            return GetMiscWeather200ResponseLifeIndicesUv(
        )
        """

    def testGetMiscWeather200ResponseLifeIndicesUv(self):
        """Test GetMiscWeather200ResponseLifeIndicesUv"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
