# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_ai_translate200_response import PostAiTranslate200Response

class TestPostAiTranslate200Response(unittest.TestCase):
    """PostAiTranslate200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAiTranslate200Response:
        """Test PostAiTranslate200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAiTranslate200Response`
        """
        model = PostAiTranslate200Response()
        if include_optional:
            return PostAiTranslate200Response(
                code = 200,
                message = 'Translation completed successfully',
                is_batch = False,
                data = uapi.models.post_ai_translate_200_response_data.post_ai_translate_200_response_data(
                    original_text = 'Hello, how are you today?', 
                    translated_text = '你好，你今天怎么样？', 
                    detected_lang = 'en', 
                    confidence_score = 0.98, 
                    alternatives = ["你好，今天过得如何？"], 
                    explanation = uapi.models.post_ai_translate_200_response_data_explanation.post_ai_translate_200_response_data_explanation(
                        key_phrases = [
                            None
                            ], 
                        cultural_notes = [
                            ''
                            ], 
                        grammar_notes = [
                            ''
                            ], ), ),
                batch_data = [
                    uapi.models.post_ai_translate_200_response_batch_data_inner.post_ai_translate_200_response_batch_data_inner(
                        original_text = '', 
                        translated_text = '', 
                        confidence_score = 1.337, )
                    ],
                batch_summary = uapi.models.post_ai_translate_200_response_batch_summary.post_ai_translate_200_response_batch_summary(
                    total_items = 56, 
                    success_items = 56, 
                    failed_items = 56, 
                    average_quality = 1.337, ),
                performance = uapi.models.post_ai_translate_200_response_performance.post_ai_translate_200_response_performance(
                    processing_time_ms = 850, 
                    cache_hit = False, ),
                quality_metrics = uapi.models.post_ai_translate_200_response_quality_metrics.post_ai_translate_200_response_quality_metrics(
                    fluency_score = 0.95, 
                    accuracy_score = 0.92, 
                    completeness_score = 0.98, 
                    total_score = 0.95, )
            )
        else:
            return PostAiTranslate200Response(
        )
        """

    def testPostAiTranslate200Response(self):
        """Test PostAiTranslate200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
