# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_misc_weather200_response_life_indices_comfort import GetMiscWeather200ResponseLifeIndicesComfort

class TestGetMiscWeather200ResponseLifeIndicesComfort(unittest.TestCase):
    """GetMiscWeather200ResponseLifeIndicesComfort unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMiscWeather200ResponseLifeIndicesComfort:
        """Test GetMiscWeather200ResponseLifeIndicesComfort
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMiscWeather200ResponseLifeIndicesComfort`
        """
        model = GetMiscWeather200ResponseLifeIndicesComfort()
        if include_optional:
            return GetMiscWeather200ResponseLifeIndicesComfort(
                level = '冷',
                brief = '偏冷',
                advice = '体感偏冷，适当添加衣物'
            )
        else:
            return GetMiscWeather200ResponseLifeIndicesComfort(
        )
        """

    def testGetMiscWeather200ResponseLifeIndicesComfort(self):
        """Test GetMiscWeather200ResponseLifeIndicesComfort"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
