# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.api.translate_api import TranslateApi


class TestTranslateApi(unittest.TestCase):
    """TranslateApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TranslateApi()

    def tearDown(self) -> None:
        pass

    def test_get_ai_translate_languages(self) -> None:
        """Test case for get_ai_translate_languages

        获取AI翻译支持的语言和配置
        """
        pass

    def test_post_ai_translate(self) -> None:
        """Test case for post_ai_translate

        AI智能翻译
        """
        pass

    def test_post_translate_text(self) -> None:
        """Test case for post_translate_text

        多语言文本翻译
        """
        pass


if __name__ == '__main__':
    unittest.main()
