# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.get_history_programmer200_response_events_inner import GetHistoryProgrammer200ResponseEventsInner

class TestGetHistoryProgrammer200ResponseEventsInner(unittest.TestCase):
    """GetHistoryProgrammer200ResponseEventsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetHistoryProgrammer200ResponseEventsInner:
        """Test GetHistoryProgrammer200ResponseEventsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetHistoryProgrammer200ResponseEventsInner`
        """
        model = GetHistoryProgrammer200ResponseEventsInner()
        if include_optional:
            return GetHistoryProgrammer200ResponseEventsInner(
                year = 1968,
                title = 'ASCII 标准发布',
                description = '美国信息交换标准代码正式发布，成为计算机文本编码的基础',
                category = '技术标准',
                importance = 8,
                relevance_score = 0.92,
                url = 'https://zh.wikipedia.org/wiki/ASCII'
            )
        else:
            return GetHistoryProgrammer200ResponseEventsInner(
        )
        """

    def testGetHistoryProgrammer200ResponseEventsInner(self):
        """Test GetHistoryProgrammer200ResponseEventsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
