# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_ai_translate200_response_batch_data_inner import PostAiTranslate200ResponseBatchDataInner

class TestPostAiTranslate200ResponseBatchDataInner(unittest.TestCase):
    """PostAiTranslate200ResponseBatchDataInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostAiTranslate200ResponseBatchDataInner:
        """Test PostAiTranslate200ResponseBatchDataInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostAiTranslate200ResponseBatchDataInner`
        """
        model = PostAiTranslate200ResponseBatchDataInner()
        if include_optional:
            return PostAiTranslate200ResponseBatchDataInner(
                original_text = '',
                translated_text = '',
                confidence_score = 1.337
            )
        else:
            return PostAiTranslate200ResponseBatchDataInner(
        )
        """

    def testPostAiTranslate200ResponseBatchDataInner(self):
        """Test PostAiTranslate200ResponseBatchDataInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
