# coding: utf-8

"""
    UAPI

    UAPI 官方接口文档

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from uapi.models.post_text_convert_request import PostTextConvertRequest

class TestPostTextConvertRequest(unittest.TestCase):
    """PostTextConvertRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostTextConvertRequest:
        """Test PostTextConvertRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostTextConvertRequest`
        """
        model = PostTextConvertRequest()
        if include_optional:
            return PostTextConvertRequest(
                text = 'hello world',
                var_from = 'plain',
                to = 'base64',
                options = { }
            )
        else:
            return PostTextConvertRequest(
                text = 'hello world',
                var_from = 'plain',
                to = 'base64',
        )
        """

    def testPostTextConvertRequest(self):
        """Test PostTextConvertRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
